"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const admin = require("firebase-admin");
const AddAssociation = require("./ar-modules/add-association");
const AddVehicleOwner = require("./ar-modules/add-vehicle-owner");
const AddVehicleType = require("./ar-modules/add-vehicle.type");
const CheckLogs = require("./ar-modules/check-logs");
const AddLandmark = require("./ar-modules/add-landmark");
const AddRoute = require("./ar-modules/add-route");
const AddCountry = require("./ar-modules/add-country");
const AddVehicle = require("./ar-modules/add-vehicle");
const RegisterUser = require("./ar-modules/register-user");
const RegisterCommuter = require("./ar-modules/register-commuter");
const UpdateAssociation = require("./ar-modules/update-association");
const BroadcastRouteUpdate = require("./ar-modules/broadcast-route-update");
admin.initializeApp();
exports.addLandmark = AddLandmark.addLandmark;
exports.addRoute = AddRoute.addRoute;
exports.addCountry = AddCountry.addCountry;
exports.addAssociation = AddAssociation.addAssociation;
exports.checkLogs = CheckLogs.checkLogs;
exports.addVehicleOwner = AddVehicleOwner.addVehicleOwner;
exports.addVehicle = AddVehicle.addVehicle;
exports.addVehicleType = AddVehicleType.addVehicleType;
exports.registerUser = RegisterUser.registerUser;
exports.registerCommuter = RegisterCommuter.registerCommuter;
exports.updateAssociation = UpdateAssociation.updateAssociation;
exports.broadcastRouteUpdate = BroadcastRouteUpdate.broadcastRouteUpdate;
//# sourceMappingURL=index.js.map