
/*
####### Generated by JavaToDart Wed Dec 19 22:12:26 SAST 2018
####### rigged up by AM Esq.
*/

class AssociationDTO {
	String associationID;
	String cityID;
	String countryID;
	String associationName;
	String phone;
	String status;
	String countryName;
	String cityName;
	String stringDate;
	int date;
	String path;

AssociationDTO({
	this.associationID,
	this.cityID,
	this.countryID,
	this.associationName,
	this.phone,
	this.status,
	this.countryName,
	this.cityName,
	this.stringDate,
	this.date,
});

AssociationDTO.fromJson(Map data) {
	this.associationID = data['associationID'];
	this.cityID = data['cityID'];
	this.countryID = data['countryID'];
	this.associationName = data['associationName'];
	this.phone = data['phone'];
	this.status = data['status'];
	this.countryName = data['countryName'];
	this.cityName = data['cityName'];
	this.stringDate = data['stringDate'];
	this.date = data['date'];
	this.path = data['path'];
}

Map<String, dynamic> toJson() => <String, dynamic>{
	'associationID': associationID,
	'cityID': cityID,
	'countryID': countryID,
	'associationName': associationName,
	'phone': phone,
	'status': status,
	'countryName': countryName,
	'cityName': cityName,
	'stringDate': stringDate,
	'date': date,
	'path': path,
	
};

}