
/*
####### Generated by JavaToDart Tue Jan 01 17:12:32 SAST 2019
####### rigged up by AM Esq.
*/

class Namespace {
	String namespaceName;
	String servingVisibility;
	String path;

Namespace({
	this.namespaceName,
	this.servingVisibility,
});

Namespace.fromJson(Map data) {
	this.namespaceName = data['namespaceName'];
	this.servingVisibility = data['servingVisibility'];
	this.path = data['path'];
}

Map<String, dynamic> toJson() => <String, dynamic>{
	'namespaceName': namespaceName,
	'servingVisibility': servingVisibility,
	'path': path,
	
};

}