
/*
####### Generated by JavaToDart Tue Jan 01 17:12:32 SAST 2019
####### rigged up by AM Esq.
*/

class Bag {
	List beacons;
	String nextPageToken;
	String totalCount;
	String path;

Bag({
	this.beacons,
	this.nextPageToken,
	this.totalCount,
});

Bag.fromJson(Map data) {
  if (data['beacons'] != null) {
    beacons = List();
    Map map = data['beacons'];
    map.forEach((key,m) {
      beacons.add(m);
    });
  }
	this.nextPageToken = data['nextPageToken'];
	this.totalCount = data['totalCount'];
	this.path = data['path'];
}

Map<String, dynamic> toJson() => <String, dynamic>{
	'beacons': beacons,
	'nextPageToken': nextPageToken,
	'totalCount': totalCount,
	'path': path,
	
};

}