
/*
####### Generated by JavaToDart Tue Jan 01 17:17:17 SAST 2019
####### rigged up by AM Esq.
*/

class IndoorLevel {
	String name;
	String path;

IndoorLevel({
	this.name,
});

IndoorLevel.fromJson(Map data) {
	this.name = data['name'];
	this.path = data['path'];
}

Map<String, dynamic> toJson() => <String, dynamic>{
	'name': name,
	'path': path,
	
};

}