
/*
####### Generated by JavaToDart Tue Jan 01 17:12:32 SAST 2019
####### rigged up by AM Esq.
*/
class Properties {
  Map<String, dynamic> vehicle;
  Map<String, dynamic> landmark;
  Properties({this.vehicle, this.landmark});

  Properties.fromJson(Map data) {
    vehicle = data['vehicle'];
    landmark = data['landmark'];
  }
  Map<String, dynamic> toJson() {
    Map<String, dynamic> map = {
      'vehicle': vehicle,
      'landmark': landmark,
    };
    return map;
  }
}
