name: migrator4
description: Data Generation for AR

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  aftarobotlibrary:
    path: /Users/mac/Documents/GitHub/aftarobot2019/aftarobotLibrary/aftarobotlibrary
#  googleapis_auth: ^0.2.6
#  permission_handler: ^2.1.2

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  simple_auth_generator:
  build_runner: ^1.1.2

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - assets/fincash.jpg
    - assets/fin3.jpeg
    - assets/computers.png
    - auth_client_keys.json
  fonts:
    - family: Raleway
      fonts:
        - asset: fonts/Raleway-Regular.ttf
        - asset: fonts/Raleway-Italic.ttf
        - asset: fonts/Raleway-ExtraBold.ttf
        - asset: fonts/Raleway-Bold.ttf
    - family: RobotoMono
      fonts:
        - asset: fonts/Roboto-Regular.ttf
        - asset: fonts/Roboto-Bold.ttf
    - family: Rubik
      fonts:
        - asset: fonts/Rubik-Regular.ttf
        - asset: fonts/Rubik-Bold.ttf
        - asset: fonts/Rubik-Black.ttf
        - asset: fonts/Rubik-Light.ttf
        - asset: fonts/Rubik-Italic.ttf
        - asset: fonts/Rubik-Medium.ttf
