import 'package:aftarobotlibrary3/data/devicedto.dart';

/*
####### Generated by JavaToDart Wed Dec 19 22:12:26 SAST 2018
####### rigged up by AM Esq.
*/

class ApologyDTO {
  String apologyID;
  String userID;
  String uid;
  String fcmToken;
  String stackTrace;
  String stringDate;
  String userMessage;
  int date;
  bool problemResolvedSent;
  double version;
  int versionCode;
  DeviceDTO device;
  String path;

  ApologyDTO({
    this.apologyID,
    this.userID,
    this.uid,
    this.fcmToken,
    this.stackTrace,
    this.stringDate,
    this.userMessage,
    this.date,
    this.problemResolvedSent,
    this.version,
    this.versionCode,
    this.device,
  });

  ApologyDTO.fromJson(Map data) {
    this.apologyID = data['apologyID'];
    this.userID = data['userID'];
    this.uid = data['uid'];
    this.fcmToken = data['fcmToken'];
    this.stackTrace = data['stackTrace'];
    this.stringDate = data['stringDate'];
    this.userMessage = data['userMessage'];
    this.date = data['date'];
    this.problemResolvedSent = data['problemResolvedSent'];
    this.version = data['version'];
    this.versionCode = data['versionCode'];
    this.device = data['device'];
    this.path = data['path'];
  }

  Map<String, dynamic> toJson() => <String, dynamic>{
        'apologyID': apologyID,
        'userID': userID,
        'uid': uid,
        'fcmToken': fcmToken,
        'stackTrace': stackTrace,
        'stringDate': stringDate,
        'userMessage': userMessage,
        'date': date,
        'problemResolvedSent': problemResolvedSent,
        'version': version,
        'versionCode': versionCode,
        'device': device,
        'path': path,
      };
}
