
/*
####### Generated by JavaToDart Wed Dec 19 22:12:26 SAST 2018
####### rigged up by AM Esq.
*/

class AttachmentDTO {
	String cityID;
	String routeID;
	String beaconName;
	String landmarkID;
	String landmarkName;
	String routeName;
	String cityName;
	int dateRegistered;
	String path;

AttachmentDTO({
	this.cityID,
	this.routeID,
	this.beaconName,
	this.landmarkID,
	this.landmarkName,
	this.routeName,
	this.cityName,
	this.dateRegistered,
});

AttachmentDTO.fromJson(Map data) {
	this.cityID = data['cityID'];
	this.routeID = data['routeID'];
	this.beaconName = data['beaconName'];
	this.landmarkID = data['landmarkID'];
	this.landmarkName = data['landmarkName'];
	this.routeName = data['routeName'];
	this.cityName = data['cityName'];
	this.dateRegistered = data['dateRegistered'];
	this.path = data['path'];
}

Map<String, dynamic> toJson() => <String, dynamic>{
	'cityID': cityID,
	'routeID': routeID,
	'beaconName': beaconName,
	'landmarkID': landmarkID,
	'landmarkName': landmarkName,
	'routeName': routeName,
	'cityName': cityName,
	'dateRegistered': dateRegistered,
	'path': path,
	
};

}