
/*
####### Generated by JavaToDart Wed Dec 19 22:12:26 SAST 2018
####### rigged up by AM Esq.
*/

class AttachmentForVehicleDTO {
	String vehicleID;
	String vehicleReg;
	String associationID;
	String ownerID;
	String beaconName;
	String associationName;
	String make;
	String model;
	int capacity;
	String path;

AttachmentForVehicleDTO({
	this.vehicleID,
	this.vehicleReg,
	this.associationID,
	this.ownerID,
	this.beaconName,
	this.associationName,
	this.make,
	this.model,
	this.capacity,
});

AttachmentForVehicleDTO.fromJson(Map data) {
	this.vehicleID = data['vehicleID'];
	this.vehicleReg = data['vehicleReg'];
	this.associationID = data['associationID'];
	this.ownerID = data['ownerID'];
	this.beaconName = data['beaconName'];
	this.associationName = data['associationName'];
	this.make = data['make'];
	this.model = data['model'];
	this.capacity = data['capacity'];
	this.path = data['path'];
}

Map<String, dynamic> toJson() => <String, dynamic>{
	'vehicleID': vehicleID,
	'vehicleReg': vehicleReg,
	'associationID': associationID,
	'ownerID': ownerID,
	'beaconName': beaconName,
	'associationName': associationName,
	'make': make,
	'model': model,
	'capacity': capacity,
	'path': path,
	
};

}