
/*
####### Generated by JavaToDart Wed Dec 19 22:12:26 SAST 2018
####### rigged up by AM Esq.
*/

class BeaconLogDTO {
	String beaconName;
	String vehicleID;
	String updatedBy;
	String stringDate;
	String vehicleReg;
	String associationID;
	String associationName;
	int date;
	bool removedFromVehicle;
	bool addedToVehicle;
	String path;

BeaconLogDTO({
	this.beaconName,
	this.vehicleID,
	this.updatedBy,
	this.stringDate,
	this.vehicleReg,
	this.associationID,
	this.associationName,
	this.date,
	this.removedFromVehicle,
	this.addedToVehicle,
});

BeaconLogDTO.fromJson(Map data) {
	this.beaconName = data['beaconName'];
	this.vehicleID = data['vehicleID'];
	this.updatedBy = data['updatedBy'];
	this.stringDate = data['stringDate'];
	this.vehicleReg = data['vehicleReg'];
	this.associationID = data['associationID'];
	this.associationName = data['associationName'];
	this.date = data['date'];
	this.removedFromVehicle = data['removedFromVehicle'];
	this.addedToVehicle = data['addedToVehicle'];
	this.path = data['path'];
}

Map<String, dynamic> toJson() => <String, dynamic>{
	'beaconName': beaconName,
	'vehicleID': vehicleID,
	'updatedBy': updatedBy,
	'stringDate': stringDate,
	'vehicleReg': vehicleReg,
	'associationID': associationID,
	'associationName': associationName,
	'date': date,
	'removedFromVehicle': removedFromVehicle,
	'addedToVehicle': addedToVehicle,
	'path': path,
	
};

}