import 'package:aftarobotlibrary3/data/userdto.dart';
import 'package:aftarobotlibrary3/data/vehicledto.dart';

/*
####### Generated by JavaToDart Wed Dec 19 22:12:26 SAST 2018
####### rigged up by AM Esq.
*/

class CommuterTripLogDTO {
  VehicleDTO vehicle;
  int date;
  String commuterTripLogID;
  String userID;
  String vehicleID;
  String routeID;
  String routeName;
  String stringDate;
  double latitude;
  double longitude;
  UserDTO commuter;
  double accuracy;
  String path;

  CommuterTripLogDTO({
    this.vehicle,
    this.date,
    this.commuterTripLogID,
    this.userID,
    this.vehicleID,
    this.routeID,
    this.routeName,
    this.stringDate,
    this.latitude,
    this.longitude,
    this.commuter,
    this.accuracy,
  });

  CommuterTripLogDTO.fromJson(Map data) {
    this.vehicle = data['vehicle'];
    this.date = data['date'];
    this.commuterTripLogID = data['commuterTripLogID'];
    this.userID = data['userID'];
    this.vehicleID = data['vehicleID'];
    this.routeID = data['routeID'];
    this.routeName = data['routeName'];
    this.stringDate = data['stringDate'];
    this.latitude = data['latitude'];
    this.longitude = data['longitude'];
    this.commuter = data['commuter'];
    this.accuracy = data['accuracy'];
    this.path = data['path'];
  }

  Map<String, dynamic> toJson() => <String, dynamic>{
        'vehicle': vehicle,
        'date': date,
        'commuterTripLogID': commuterTripLogID,
        'userID': userID,
        'vehicleID': vehicleID,
        'routeID': routeID,
        'routeName': routeName,
        'stringDate': stringDate,
        'latitude': latitude,
        'longitude': longitude,
        'commuter': commuter,
        'accuracy': accuracy,
        'path': path,
      };
}
