import 'package:aftarobotlibrary3/data/devicedto.dart';
import 'package:aftarobotlibrary3/data/userdto.dart';

/*
####### Generated by JavaToDart Wed Dec 19 22:12:26 SAST 2018
####### rigged up by AM Esq.
*/

class CommuterArrivalDTO {
  String stringDate;
  String arrivalID;
  String landmarkID;
  String landmarkName;
  String userID;
  String cityID;
  String cityName;
  String routeID;
  String vehicleID;
  String countryID;
  int dateArrived;
  UserDTO user;
  double latitude;
  double longitude;
  DeviceDTO device;
  String routeName;
  String associationName;
  String associationID;
  String path;

  CommuterArrivalDTO({
    this.stringDate,
    this.arrivalID,
    this.landmarkID,
    this.landmarkName,
    this.userID,
    this.cityID,
    this.cityName,
    this.routeID,
    this.vehicleID,
    this.countryID,
    this.dateArrived,
    this.user,
    this.latitude,
    this.longitude,
    this.device,
    this.routeName,
    this.associationName,
    this.associationID,
  });

  CommuterArrivalDTO.fromJson(Map data) {
    this.stringDate = data['stringDate'];
    this.arrivalID = data['arrivalID'];
    this.landmarkID = data['landmarkID'];
    this.landmarkName = data['landmarkName'];
    this.userID = data['userID'];
    this.cityID = data['cityID'];
    this.cityName = data['cityName'];
    this.routeID = data['routeID'];
    this.vehicleID = data['vehicleID'];
    this.countryID = data['countryID'];
    this.dateArrived = data['dateArrived'];
    this.user = data['user'];
    this.latitude = data['latitude'];
    this.longitude = data['longitude'];
    this.device = data['device'];
    this.routeName = data['routeName'];
    this.associationName = data['associationName'];
    this.associationID = data['associationID'];
    this.path = data['path'];
  }

  Map<String, dynamic> toJson() => <String, dynamic>{
        'stringDate': stringDate,
        'arrivalID': arrivalID,
        'landmarkID': landmarkID,
        'landmarkName': landmarkName,
        'userID': userID,
        'cityID': cityID,
        'cityName': cityName,
        'routeID': routeID,
        'vehicleID': vehicleID,
        'countryID': countryID,
        'dateArrived': dateArrived,
        'user': user,
        'latitude': latitude,
        'longitude': longitude,
        'device': device,
        'routeName': routeName,
        'associationName': associationName,
        'associationID': associationID,
        'path': path,
      };
}
