
/*
####### Generated by JavaToDart Wed Dec 19 22:12:26 SAST 2018
####### rigged up by AM Esq.
*/

class CommuterDTO {
	int commuterID;
	String gcmID;
	String name;
	String surname;
	String phone;
	String email;
	String password;
	String status;
	int date;
	List photos;
	String path;

CommuterDTO({
	this.commuterID,
	this.gcmID,
	this.name,
	this.surname,
	this.phone,
	this.email,
	this.password,
	this.status,
	this.date,
});

CommuterDTO.fromJson(Map data) {
	this.commuterID = data['commuterID'];
	this.gcmID = data['gcmID'];
	this.name = data['name'];
	this.surname = data['surname'];
	this.phone = data['phone'];
	this.email = data['email'];
	this.password = data['password'];
	this.status = data['status'];
	this.date = data['date'];
	this.path = data['path'];
}

Map<String, dynamic> toJson() => <String, dynamic>{
	'commuterID': commuterID,
	'gcmID': gcmID,
	'name': name,
	'surname': surname,
	'phone': phone,
	'email': email,
	'password': password,
	'status': status,
	'date': date,
	'path': path,
	
};

}