
/*
####### Generated by JavaToDart Wed Dec 19 22:12:26 SAST 2018
####### rigged up by AM Esq.
*/

class CommuterFinishedWalkingDTO {
	String userID;
	String stringDate;
	String finishedWalkingID;
	double latitude;
	double longitude;
	int date;
	String path;

CommuterFinishedWalkingDTO({
	this.userID,
	this.stringDate,
	this.finishedWalkingID,
	this.latitude,
	this.longitude,
	this.date,
});

CommuterFinishedWalkingDTO.fromJson(Map data) {
	this.userID = data['userID'];
	this.stringDate = data['stringDate'];
	this.finishedWalkingID = data['finishedWalkingID'];
	this.latitude = data['latitude'];
	this.longitude = data['longitude'];
	this.date = data['date'];
	this.path = data['path'];
}

Map<String, dynamic> toJson() => <String, dynamic>{
	'userID': userID,
	'stringDate': stringDate,
	'finishedWalkingID': finishedWalkingID,
	'latitude': latitude,
	'longitude': longitude,
	'date': date,
	'path': path,
	
};

}