
/*
####### Generated by JavaToDart Wed Dec 19 22:12:26 SAST 2018
####### rigged up by AM Esq.
*/

class DriverFinishedWalkingDTO {
	String driverWalkingID;
	String driverID;
	String name;
	String associationID;
	String associationName;
	String stringDate;
	int date;
	double latitude;
	double longitude;
	String path;

DriverFinishedWalkingDTO({
	this.driverWalkingID,
	this.driverID,
	this.name,
	this.associationID,
	this.associationName,
	this.stringDate,
	this.date,
	this.latitude,
	this.longitude,
});

DriverFinishedWalkingDTO.fromJson(Map data) {
	this.driverWalkingID = data['driverWalkingID'];
	this.driverID = data['driverID'];
	this.name = data['name'];
	this.associationID = data['associationID'];
	this.associationName = data['associationName'];
	this.stringDate = data['stringDate'];
	this.date = data['date'];
	this.latitude = data['latitude'];
	this.longitude = data['longitude'];
	this.path = data['path'];
}

Map<String, dynamic> toJson() => <String, dynamic>{
	'driverWalkingID': driverWalkingID,
	'driverID': driverID,
	'name': name,
	'associationID': associationID,
	'associationName': associationName,
	'stringDate': stringDate,
	'date': date,
	'latitude': latitude,
	'longitude': longitude,
	'path': path,
	
};

}