
/*
####### Generated by JavaToDart Wed Dec 19 22:12:26 SAST 2018
####### rigged up by AM Esq.
*/

class FavouriteDTO {
	int favouriteID;
	int commuterID;
	int cityID;
	int date;
	String status;
	String path;

FavouriteDTO({
	this.favouriteID,
	this.commuterID,
	this.cityID,
	this.date,
	this.status,
});

FavouriteDTO.fromJson(Map data) {
	this.favouriteID = data['favouriteID'];
	this.commuterID = data['commuterID'];
	this.cityID = data['cityID'];
	this.date = data['date'];
	this.status = data['status'];
	this.path = data['path'];
}

Map<String, dynamic> toJson() => <String, dynamic>{
	'favouriteID': favouriteID,
	'commuterID': commuterID,
	'cityID': cityID,
	'date': date,
	'status': status,
	'path': path,
	
};

}