import 'package:aftarobotlibrary3/data/vehicledto.dart';

/*
####### Generated by JavaToDart Wed Dec 19 22:12:26 SAST 2018
####### rigged up by AM Esq.
*/

class FullTaxiDTO {
  String associationID;
  String ownerID;
  String driverID;
  String marshalID;
  String vehicleID;
  String stringDate;
  String associationName;
  String ownerName;
  String driverName;
  String marshalName;
  int date;
  VehicleDTO vehicle;
  double latitude;
  double longitude;
  String path;

  FullTaxiDTO({
    this.associationID,
    this.ownerID,
    this.driverID,
    this.marshalID,
    this.vehicleID,
    this.stringDate,
    this.associationName,
    this.ownerName,
    this.driverName,
    this.marshalName,
    this.date,
    this.vehicle,
    this.latitude,
    this.longitude,
  });

  FullTaxiDTO.fromJson(Map data) {
    this.associationID = data['associationID'];
    this.ownerID = data['ownerID'];
    this.driverID = data['driverID'];
    this.marshalID = data['marshalID'];
    this.vehicleID = data['vehicleID'];
    this.stringDate = data['stringDate'];
    this.associationName = data['associationName'];
    this.ownerName = data['ownerName'];
    this.driverName = data['driverName'];
    this.marshalName = data['marshalName'];
    this.date = data['date'];
    this.vehicle = data['vehicle'];
    this.latitude = data['latitude'];
    this.longitude = data['longitude'];
    this.path = data['path'];
  }

  Map<String, dynamic> toJson() => <String, dynamic>{
        'associationID': associationID,
        'ownerID': ownerID,
        'driverID': driverID,
        'marshalID': marshalID,
        'vehicleID': vehicleID,
        'stringDate': stringDate,
        'associationName': associationName,
        'ownerName': ownerName,
        'driverName': driverName,
        'marshalName': marshalName,
        'date': date,
        'vehicle': vehicle,
        'latitude': latitude,
        'longitude': longitude,
        'path': path,
      };
}
