import 'package:aftarobotlibrary3/data/userdto.dart';
import 'package:aftarobotlibrary3/data/vehicledto.dart';

/*
####### Generated by JavaToDart Wed Dec 19 22:12:26 SAST 2018
####### rigged up by AM Esq.
*/

class IncidentDTO {
  String incidentID;
  String description;
  String associationID;
  String routeID;
  String landmarkID;
  String routeName;
  String landmarkName;
  String associationName;
  String incidentType;
  String fcmToken;
  String stringDate;
  String countryID;
  double latitude;
  double longitude;
  String address;
  UserDTO patroller;
  UserDTO administrator;
  UserDTO marshal;
  int date;
  int dateReported;
  String path;
  List<VehicleDTO> vehicles;

  IncidentDTO({
    this.incidentID,
    this.description,
    this.associationID,
    this.routeID,
    this.landmarkID,
    this.routeName,
    this.landmarkName,
    this.associationName,
    this.incidentType,
    this.fcmToken,
    this.stringDate,
    this.countryID,
    this.latitude,
    this.longitude,
    this.address,
    this.patroller,
    this.marshal,
    this.administrator,
    this.vehicles,
    this.date,
    this.dateReported,
  });

  IncidentDTO.fromJson(Map data) {
    this.incidentID = data['incidentID'];
    this.description = data['description'];
    this.associationID = data['associationID'];
    this.routeID = data['routeID'];
    this.landmarkID = data['landmarkID'];
    this.routeName = data['routeName'];
    this.landmarkName = data['landmarkName'];
    this.associationName = data['associationName'];
    this.incidentType = data['incidentType'];
    this.fcmToken = data['fcmToken'];
    this.stringDate = data['stringDate'];
    this.countryID = data['countryID'];
    this.latitude = data['latitude'];
    this.longitude = data['longitude'];
    this.address = data['address'];
    this.patroller = data['patroller'];
    this.marshal = data['marshal'];
    this.administrator = data['administrator'];
    this.vehicles = data['vehicles'];
    this.date = data['date'];
    this.dateReported = data['dateReported'];
    this.path = data['path'];
  }

  Map<String, dynamic> toJson() => <String, dynamic>{
        'incidentID': incidentID,
        'description': description,
        'associationID': associationID,
        'routeID': routeID,
        'landmarkID': landmarkID,
        'routeName': routeName,
        'landmarkName': landmarkName,
        'associationName': associationName,
        'incidentType': incidentType,
        'fcmToken': fcmToken,
        'stringDate': stringDate,
        'countryID': countryID,
        'latitude': latitude,
        'longitude': longitude,
        'address': address,
        'patroller': patroller,
        'marshal': marshal,
        'administrator': administrator,
        'vehicles': vehicles,
        'date': date,
        'dateReported': dateReported,
        'path': path,
      };
}
