
/*
####### Generated by JavaToDart Wed Dec 19 22:12:26 SAST 2018
####### rigged up by AM Esq.
*/

class MarshalLandmarkDTO {
	String userID;
	String landmarkID;
	String associationID;
	String landmarkName;
	String marshalName;
	String stringDate;
	int date;
	String path;

MarshalLandmarkDTO({
	this.userID,
	this.landmarkID,
	this.associationID,
	this.landmarkName,
	this.marshalName,
	this.stringDate,
	this.date,
});

MarshalLandmarkDTO.fromJson(Map data) {
	this.userID = data['userID'];
	this.landmarkID = data['landmarkID'];
	this.associationID = data['associationID'];
	this.landmarkName = data['landmarkName'];
	this.marshalName = data['marshalName'];
	this.stringDate = data['stringDate'];
	this.date = data['date'];
	this.path = data['path'];
}

Map<String, dynamic> toJson() => <String, dynamic>{
	'userID': userID,
	'landmarkID': landmarkID,
	'associationID': associationID,
	'landmarkName': landmarkName,
	'marshalName': marshalName,
	'stringDate': stringDate,
	'date': date,
	'path': path,
	
};

}