/*
####### Generated by JavaToDart Wed Dec 19 22:12:26 SAST 2018
####### rigged up by AM Esq.
*/

import 'package:aftarobotlibrary3/data/travelbuddydto.dart';

class PanicDTO {
  String userID;
  String fcmToken;
  String stringDate;
  String panicID;
  String userName;
  int date;
  double latitude;
  double longitude;
  String panicType;
  String path;
  List<TravelBuddyDTO> travelBuddies;

  PanicDTO({
    this.userID,
    this.fcmToken,
    this.stringDate,
    this.panicID,
    this.userName,
    this.date,
    this.latitude,
    this.longitude,
    this.panicType,
    this.travelBuddies,
  });

  PanicDTO.fromJson(Map data) {
    this.userID = data['userID'];
    this.fcmToken = data['fcmToken'];
    this.stringDate = data['stringDate'];
    this.panicID = data['panicID'];
    this.userName = data['userName'];
    this.date = data['date'];
    this.latitude = data['latitude'];
    this.longitude = data['longitude'];
    this.panicType = data['panicType'];
    this.travelBuddies = data['travelBuddies'];
    this.path = data['path'];
  }

  Map<String, dynamic> toJson() => <String, dynamic>{
        'userID': userID,
        'fcmToken': fcmToken,
        'stringDate': stringDate,
        'panicID': panicID,
        'userName': userName,
        'date': date,
        'latitude': latitude,
        'longitude': longitude,
        'panicType': panicType,
        'travelBuddies': travelBuddies,
        'path': path,
      };
}
