
/*
####### Generated by JavaToDart Wed Dec 19 22:12:26 SAST 2018
####### rigged up by AM Esq.
*/

class PatrollerDTO {
	int patrollerID;
	String gcmID;
	String address;
	String name;
	String associationID;
	String countryID;
	String email;
	String phone;
	String password;
	String status;
	String idNo;
	int date;
	String path;

PatrollerDTO({
	this.patrollerID,
	this.gcmID,
	this.address,
	this.name,
	this.associationID,
	this.countryID,
	this.email,
	this.phone,
	this.password,
	this.status,
	this.idNo,
	this.date,
});

PatrollerDTO.fromJson(Map data) {
	this.patrollerID = data['patrollerID'];
	this.gcmID = data['gcmID'];
	this.address = data['address'];
	this.name = data['name'];
	this.associationID = data['associationID'];
	this.countryID = data['countryID'];
	this.email = data['email'];
	this.phone = data['phone'];
	this.password = data['password'];
	this.status = data['status'];
	this.idNo = data['idNo'];
	this.date = data['date'];
	this.path = data['path'];
}

Map<String, dynamic> toJson() => <String, dynamic>{
	'patrollerID': patrollerID,
	'gcmID': gcmID,
	'address': address,
	'name': name,
	'associationID': associationID,
	'countryID': countryID,
	'email': email,
	'phone': phone,
	'password': password,
	'status': status,
	'idNo': idNo,
	'date': date,
	'path': path,
	
};

}