
/*
####### Generated by JavaToDart Wed Dec 19 22:12:26 SAST 2018
####### rigged up by AM Esq.
*/

class ProblemResolvedDTO {
	String problemResolvedID;
	String userID;
	String message;
	String fcmToken;
	String stringDate;
	String stringProblemDate;
	int date;
	int problemDate;
	String apologyID;
	String path;

ProblemResolvedDTO({
	this.problemResolvedID,
	this.userID,
	this.message,
	this.fcmToken,
	this.stringDate,
	this.stringProblemDate,
	this.date,
	this.problemDate,
	this.apologyID,
});

ProblemResolvedDTO.fromJson(Map data) {
	this.problemResolvedID = data['problemResolvedID'];
	this.userID = data['userID'];
	this.message = data['message'];
	this.fcmToken = data['fcmToken'];
	this.stringDate = data['stringDate'];
	this.stringProblemDate = data['stringProblemDate'];
	this.date = data['date'];
	this.problemDate = data['problemDate'];
	this.apologyID = data['apologyID'];
	this.path = data['path'];
}

Map<String, dynamic> toJson() => <String, dynamic>{
	'problemResolvedID': problemResolvedID,
	'userID': userID,
	'message': message,
	'fcmToken': fcmToken,
	'stringDate': stringDate,
	'stringProblemDate': stringProblemDate,
	'date': date,
	'problemDate': problemDate,
	'apologyID': apologyID,
	'path': path,
	
};

}