
/*
####### Generated by JavaToDart Wed Dec 19 22:12:26 SAST 2018
####### rigged up by AM Esq.
*/

class RatingTypeAggregateDTO {
	double count;
	double total;
	double aggregate;
	String path;

RatingTypeAggregateDTO({
	this.count,
	this.total,
	this.aggregate,
});

RatingTypeAggregateDTO.fromJson(Map data) {
	this.count = data['count'];
	this.total = data['total'];
	this.aggregate = data['aggregate'];
	this.path = data['path'];
}

Map<String, dynamic> toJson() => <String, dynamic>{
	'count': count,
	'total': total,
	'aggregate': aggregate,
	'path': path,
	
};

}