
/*
####### Generated by JavaToDart Wed Dec 19 22:12:26 SAST 2018
####### rigged up by AM Esq.
*/

class RatingTypeDTO {
	int key;
	String name;
	String path;

RatingTypeDTO({
	this.key,
	this.name,
});

RatingTypeDTO.fromJson(Map data) {
	this.key = data['key'];
	this.name = data['name'];
	this.path = data['path'];
}

Map<String, dynamic> toJson() => <String, dynamic>{
	'key': key,
	'name': name,
	'path': path,
	
};

}