
/*
####### Generated by JavaToDart Wed Dec 19 22:12:26 SAST 2018
####### rigged up by AM Esq.
*/

class RemoteConfigDTO {
	String driversUUID;
	String marshalsUUID;
	String patrollersUUID;
	String commutersUUID;
	String routeBuildersUUID;
	String path;

RemoteConfigDTO({
	this.driversUUID,
	this.marshalsUUID,
	this.patrollersUUID,
	this.commutersUUID,
	this.routeBuildersUUID,
});

RemoteConfigDTO.fromJson(Map data) {
	this.driversUUID = data['driversUUID'];
	this.marshalsUUID = data['marshalsUUID'];
	this.patrollersUUID = data['patrollersUUID'];
	this.commutersUUID = data['commutersUUID'];
	this.routeBuildersUUID = data['routeBuildersUUID'];
	this.path = data['path'];
}

Map<String, dynamic> toJson() => <String, dynamic>{
	'driversUUID': driversUUID,
	'marshalsUUID': marshalsUUID,
	'patrollersUUID': patrollersUUID,
	'commutersUUID': commutersUUID,
	'routeBuildersUUID': routeBuildersUUID,
	'path': path,
	
};

}