/*
####### Generated by JavaToDart Wed Dec 19 22:12:26 SAST 2018
####### rigged up by AM Esq.
*/
import 'package:aftarobotlibrary3/data/userdto.dart';

class RouteDTO {
  String routeID;
  String associationID;
  String countryID;
  String provinceID;
  String cityID;
  String name;
  String status;
  String associationName;
  String cityName;
  String countryName;
  String routeNumber;
  String stringDate;
  String color;
  int date;
  UserDTO routeBuilder;
  String path;
  bool isActive;
  String activationDate;

  RouteDTO({
    this.routeID,
    this.associationID,
    this.countryID,
    this.provinceID,
    this.cityID,
    this.name,
    this.status,
    this.associationName,
    this.cityName,
    this.countryName,
    this.routeNumber,
    this.stringDate,
    this.color,
    this.date,
    this.routeBuilder,
    this.activationDate,
    this.isActive,
  });

  RouteDTO.fromJson(Map data) {
    this.routeID = data['routeID'];
    this.associationID = data['associationID'];
    this.countryID = data['countryID'];
    this.provinceID = data['provinceID'];
    this.cityID = data['cityID'];
    this.name = data['name'];
    this.status = data['status'];
    this.associationName = data['associationName'];
    this.cityName = data['cityName'];
    this.countryName = data['countryName'];
    this.routeNumber = data['routeNumber'];
    this.stringDate = data['stringDate'];
    this.color = data['color'];
    this.date = data['date'];
    if (data['routeBuilder'] != null) {
      var map = data['routeBuilder'];
      this.routeBuilder = UserDTO.fromJson(map);
    }

    this.path = data['path'];
    this.activationDate = data['activationDate'];
    this.isActive = data['isActive'];
  }

  Map<String, dynamic> toJson() {
    var rbMap;
    if (routeBuilder != null) {
      rbMap = routeBuilder.toJson();
    }

    Map<String, dynamic> map = {
      'routeID': routeID,
      'associationID': associationID,
      'countryID': countryID,
      'provinceID': provinceID,
      'cityID': cityID,
      'name': name,
      'status': status,
      'associationName': associationName,
      'cityName': cityName,
      'countryName': countryName,
      'routeNumber': routeNumber,
      'stringDate': stringDate,
      'color': color,
      'date': date,
      'routeBuilder': rbMap,
      'activationDate': activationDate,
      'path': path,
      'isActive': isActive,
    };
    return map;
  }
}
