
/*
####### Generated by JavaToDart Wed Dec 19 22:12:26 SAST 2018
####### rigged up by AM Esq.
*/

class RouteBuilderMessageDTO {
	String routeBuilderMessageID;
	String title;
	String message;
	String stringDate;
	String from;
	String fcmToken;
	int date;
	String path;

RouteBuilderMessageDTO({
	this.routeBuilderMessageID,
	this.title,
	this.message,
	this.stringDate,
	this.from,
	this.fcmToken,
	this.date,
});

RouteBuilderMessageDTO.fromJson(Map data) {
	this.routeBuilderMessageID = data['routeBuilderMessageID'];
	this.title = data['title'];
	this.message = data['message'];
	this.stringDate = data['stringDate'];
	this.from = data['from'];
	this.fcmToken = data['fcmToken'];
	this.date = data['date'];
	this.path = data['path'];
}

Map<String, dynamic> toJson() => <String, dynamic>{
	'routeBuilderMessageID': routeBuilderMessageID,
	'title': title,
	'message': message,
	'stringDate': stringDate,
	'from': from,
	'fcmToken': fcmToken,
	'date': date,
	'path': path,
	
};

}