
/*
####### Generated by JavaToDart Wed Dec 19 22:12:26 SAST 2018
####### rigged up by AM Esq.
*/

class RouteBuilderLocationRequestDTO {
	String routeBuilderLocationRequestID;
	String from;
	String stringDate;
	String fcmToken;
	int date;
	String path;

RouteBuilderLocationRequestDTO({
	this.routeBuilderLocationRequestID,
	this.from,
	this.stringDate,
	this.fcmToken,
	this.date,
});

RouteBuilderLocationRequestDTO.fromJson(Map data) {
	this.routeBuilderLocationRequestID = data['routeBuilderLocationRequestID'];
	this.from = data['from'];
	this.stringDate = data['stringDate'];
	this.fcmToken = data['fcmToken'];
	this.date = data['date'];
	this.path = data['path'];
}

Map<String, dynamic> toJson() => <String, dynamic>{
	'routeBuilderLocationRequestID': routeBuilderLocationRequestID,
	'from': from,
	'stringDate': stringDate,
	'fcmToken': fcmToken,
	'date': date,
	'path': path,
	
};

}