import 'package:aftarobotlibrary3/data/userdto.dart';
import 'package:aftarobotlibrary3/data/vehicledto.dart';

/*
####### Generated by JavaToDart Wed Dec 19 22:12:26 SAST 2018
####### rigged up by AM Esq.
*/

class TaxiFeesDTO {
  String associationID;
  String vehicleID;
  String driverID;
  String marshalID;
  String patrollerID;
  String taxiFeesID;
  String associationName;
  String adminID;
  String ownerID;
  double amount;
  VehicleDTO vehicle;
  UserDTO driver;
  UserDTO user;
  UserDTO marshal;
  UserDTO patroller;
  UserDTO administrator;
  UserDTO owner;
  int date;
  String path;

  TaxiFeesDTO({
    this.associationID,
    this.vehicleID,
    this.driverID,
    this.marshalID,
    this.patrollerID,
    this.taxiFeesID,
    this.associationName,
    this.adminID,
    this.ownerID,
    this.amount,
    this.vehicle,
    this.driver,
    this.marshal,
    this.patroller,
    this.administrator,
    this.owner,
    this.date,
  });

  TaxiFeesDTO.fromJson(Map data) {
    this.associationID = data['associationID'];
    this.vehicleID = data['vehicleID'];
    this.driverID = data['driverID'];
    this.marshalID = data['marshalID'];
    this.patrollerID = data['patrollerID'];
    this.taxiFeesID = data['taxiFeesID'];
    this.associationName = data['associationName'];
    this.adminID = data['adminID'];
    this.ownerID = data['ownerID'];
    this.amount = data['amount'];
    this.vehicle = data['vehicle'];
    this.driver = data['driver'];
    this.marshal = data['marshal'];
    this.patroller = data['patroller'];
    this.administrator = data['administrator'];
    this.owner = data['owner'];
    this.date = data['date'];
    this.path = data['path'];
  }

  Map<String, dynamic> toJson() => <String, dynamic>{
        'associationID': associationID,
        'vehicleID': vehicleID,
        'driverID': driverID,
        'marshalID': marshalID,
        'patrollerID': patrollerID,
        'taxiFeesID': taxiFeesID,
        'associationName': associationName,
        'adminID': adminID,
        'ownerID': ownerID,
        'amount': amount,
        'vehicle': vehicle,
        'driver': driver,
        'marshal': marshal,
        'patroller': patroller,
        'administrator': administrator,
        'owner': owner,
        'date': date,
        'path': path,
      };
}
