import 'package:aftarobotlibrary3/data/vehicledto.dart';

/*
####### Generated by JavaToDart Wed Dec 19 22:12:26 SAST 2018
####### rigged up by AM Esq.
*/

class VehicleLocationResponseDTO {
  String vehicleLocationResponseID;
  String vehicleID;
  String vehicleReg;
  String userID;
  String driverID;
  String stringDate;
  String userName;
  String fcmToken;
  int date;
  double latitude;
  double longitude;
  VehicleDTO vehicle;
  String path;

  VehicleLocationResponseDTO({
    this.vehicleLocationResponseID,
    this.vehicleID,
    this.vehicleReg,
    this.userID,
    this.driverID,
    this.stringDate,
    this.userName,
    this.fcmToken,
    this.date,
    this.latitude,
    this.longitude,
    this.vehicle,
  });

  VehicleLocationResponseDTO.fromJson(Map data) {
    this.vehicleLocationResponseID = data['vehicleLocationResponseID'];
    this.vehicleID = data['vehicleID'];
    this.vehicleReg = data['vehicleReg'];
    this.userID = data['userID'];
    this.driverID = data['driverID'];
    this.stringDate = data['stringDate'];
    this.userName = data['userName'];
    this.fcmToken = data['fcmToken'];
    this.date = data['date'];
    this.latitude = data['latitude'];
    this.longitude = data['longitude'];
    this.vehicle = data['vehicle'];
    this.path = data['path'];
  }

  Map<String, dynamic> toJson() => <String, dynamic>{
        'vehicleLocationResponseID': vehicleLocationResponseID,
        'vehicleID': vehicleID,
        'vehicleReg': vehicleReg,
        'userID': userID,
        'driverID': driverID,
        'stringDate': stringDate,
        'userName': userName,
        'fcmToken': fcmToken,
        'date': date,
        'latitude': latitude,
        'longitude': longitude,
        'vehicle': vehicle,
        'path': path,
      };
}
