name: aftarobotlibrary3
description: AR Lib

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  uuid: ^1.0.3
  font_awesome_flutter: ^8.2.0
  google_sign_in: ^3.2.4
  firebase_auth: ^0.6.6
  firebase_messaging: ^2.1.0
  firebase_database: ^1.0.5
  firebase_core: ^0.2.5+1
  firebase_storage: ^1.0.4
  cloud_firestore: ^0.8.2+3
  shared_preferences: ^0.4.3
  path_provider: ^0.4.1
  intl: ^0.15.7
  http: ^0.12.0
  google_maps_flutter: ^0.0.3+3
  flutter_document_picker: ^1.2.0
  autocomplete_textfield: ^1.6.4
  permission_handler: ^2.1.2
  googleapis_auth: ^0.2.6
  google_maps_webservice: ^0.0.11
  flutter_background_geolocation:
    git:
      url: https://github.com/transistorsoft/flutter_background_geolocation

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
