
/*
####### Generated by JavaToDart Wed Dec 19 22:12:26 SAST 2018
####### rigged up by AM Esq.
*/

class AdminDTO {
	String adminID;
	String associationID;
	String countryID;
	String name;
	String phone;
	String email;
	String password;
	String status;
	String gcmID;
	int date;
	String path;

AdminDTO({
	this.adminID,
	this.associationID,
	this.countryID,
	this.name,
	this.phone,
	this.email,
	this.password,
	this.status,
	this.gcmID,
	this.date,
});

AdminDTO.fromJson(Map data) {
	this.adminID = data['adminID'];
	this.associationID = data['associationID'];
	this.countryID = data['countryID'];
	this.name = data['name'];
	this.phone = data['phone'];
	this.email = data['email'];
	this.password = data['password'];
	this.status = data['status'];
	this.gcmID = data['gcmID'];
	this.date = data['date'];
	this.path = data['path'];
}

Map<String, dynamic> toJson() => <String, dynamic>{
	'adminID': adminID,
	'associationID': associationID,
	'countryID': countryID,
	'name': name,
	'phone': phone,
	'email': email,
	'password': password,
	'status': status,
	'gcmID': gcmID,
	'date': date,
	'path': path,
	
};

}