import 'package:aftarobotlibrary/data/driveraggregateratingdto.dart';
import 'package:aftarobotlibrary/data/rankaggregateratingdto.dart';
import 'package:aftarobotlibrary/data/safetyaggregateratingdto.dart';
import 'package:aftarobotlibrary/data/vehicleaggregateratingdto.dart';

/*
####### Generated by JavaToDart Wed Dec 19 22:12:26 SAST 2018
####### rigged up by AM Esq.
*/

class AggregatesRatingsDTO {
  DriverAggregateRatingDTO driverAggregate;
//	ExperienceAggregateRatingDTO experienceAggregate;
  RankAggregateRatingDTO rankAggregate;
  SafetyAggregateRatingDTO safetyAggregate;
  VehicleAggregateRatingDTO vehicleAggregate;
  String path;

  AggregatesRatingsDTO({
    this.driverAggregate,
//    this.experienceAggregate,
    this.rankAggregate,
    this.safetyAggregate,
    this.vehicleAggregate,
  });

  AggregatesRatingsDTO.fromJson(Map data) {
    this.driverAggregate = data['driverAggregate'];
//    this.experienceAggregate = data['experienceAggregate'];
    this.rankAggregate = data['rankAggregate'];
    this.safetyAggregate = data['safetyAggregate'];
    this.vehicleAggregate = data['vehicleAggregate'];
    this.path = data['path'];
  }

  Map<String, dynamic> toJson() => <String, dynamic>{
        'driverAggregate': driverAggregate,
//        'experienceAggregate': experienceAggregate,
        'rankAggregate': rankAggregate,
        'safetyAggregate': safetyAggregate,
        'vehicleAggregate': vehicleAggregate,
        'path': path,
      };
}
