/*
####### Generated by JavaToDart Wed Dec 19 22:12:26 SAST 2018
####### rigged up by AM Esq.
*/

class BasicMessageDTO {
  String title;
  String body;
  String stringDate;
  String json;
  String from;
  int date;
  String path;

  BasicMessageDTO({
    this.title,
    this.body,
    this.stringDate,
    this.json,
    this.from,
    this.date,
  });

  BasicMessageDTO.fromJson(Map data) {
    this.title = data['title'];
    this.body = data['body'];
    this.stringDate = data['stringDate'];
    this.json = data['json'];
    this.from = data['from'];
    this.date = data['date'];
    this.path = data['path'];
  }

  Map<String, dynamic> toJson() => <String, dynamic>{
        'title': title,
        'body': body,
        'stringDate': stringDate,
        'json': json,
        'from': from,
        'date': date,
        'path': path,
      };
}
