import 'package:aftarobotlibrary/data/userdto.dart';

/*
####### Generated by JavaToDart Wed Dec 19 22:12:26 SAST 2018
####### rigged up by AM Esq.
*/

class CityDTO {
  String cityID;
  String provinceID;
  String countryID;
  String name;
  String status;
  String provinceName;
  double latitude;
  double longitude;
  String countryName;
  UserDTO user;
  int date;
  List routeList;
  List associationList;
  String path;

  CityDTO({
    this.cityID,
    this.provinceID,
    this.countryID,
    this.name,
    this.status,
    this.provinceName,
    this.latitude,
    this.longitude,
    this.countryName,
    this.date,
    this.routeList,
    this.associationList,
  });

  CityDTO.fromJson(Map data) {
    this.cityID = data['cityID'];
    this.provinceID = data['provinceID'];
    this.countryID = data['countryID'];
    this.name = data['name'];
    this.status = data['status'];
    this.provinceName = data['provinceName'];
    this.latitude = data['latitude'];
    this.longitude = data['longitude'];
    this.countryName = data['countryName'];
    this.date = data['date'];
    this.routeList = data['routeList'];
    this.associationList = data['associationList'];
    this.path = data['path'];
  }

  Map<String, dynamic> toJson() => <String, dynamic>{
        'cityID': cityID,
        'provinceID': provinceID,
        'countryID': countryID,
        'name': name,
        'status': status,
        'provinceName': provinceName,
        'latitude': latitude,
        'longitude': longitude,
        'countryName': countryName,
        'date': date,
        'routeList': routeList,
        'associationList': associationList,
        'path': path,
      };
}
