import 'package:aftarobotlibrary/data/devicedto.dart';
import 'package:aftarobotlibrary/data/userdto.dart';

/*
####### Generated by JavaToDart Wed Dec 19 22:12:26 SAST 2018
####### rigged up by AM Esq.
*/

class CommuterDepartureDTO {
	String stringDate;
	String departureID;
	String landmarkID;
	String landmarkName;
	String userID;
	String cityID;
	String cityName;
	String routeID;
	String vehicleID;
	String countryID;
	int dateDeparted;
	DeviceDTO device;
	UserDTO user;
	String path;

CommuterDepartureDTO({
	this.stringDate,
	this.departureID,
	this.landmarkID,
	this.landmarkName,
	this.userID,
	this.cityID,
	this.cityName,
	this.routeID,
	this.vehicleID,
	this.countryID,
	this.dateDeparted,
	this.device,
	this.user,
});

CommuterDepartureDTO.fromJson(Map data) {
	this.stringDate = data['stringDate'];
	this.departureID = data['departureID'];
	this.landmarkID = data['landmarkID'];
	this.landmarkName = data['landmarkName'];
	this.userID = data['userID'];
	this.cityID = data['cityID'];
	this.cityName = data['cityName'];
	this.routeID = data['routeID'];
	this.vehicleID = data['vehicleID'];
	this.countryID = data['countryID'];
	this.dateDeparted = data['dateDeparted'];
	this.device = data['device'];
	this.user = data['user'];
	this.path = data['path'];
}

Map<String, dynamic> toJson() => <String, dynamic>{
	'stringDate': stringDate,
	'departureID': departureID,
	'landmarkID': landmarkID,
	'landmarkName': landmarkName,
	'userID': userID,
	'cityID': cityID,
	'cityName': cityName,
	'routeID': routeID,
	'vehicleID': vehicleID,
	'countryID': countryID,
	'dateDeparted': dateDeparted,
	'device': device,
	'user': user,
	'path': path,
	
};

}