
/*
####### Generated by JavaToDart Wed Dec 19 22:12:26 SAST 2018
####### rigged up by AM Esq.
*/

class CommuterStartDrivingDTO {
	String commuterDrivingID;
	String userID;
	String stringDate;
	String name;
	String fcmToken;
	String beaconName;
	String vehicleID;
	String vehicleReg;
	String make;
	String model;
	bool starting;
	bool stopping;
	bool moving;
	bool beaconFound;
	int date;
	int capacity;
	double latitude;
	double longitude;
	double bearing;
	double speed;
	String path;

CommuterStartDrivingDTO({
	this.commuterDrivingID,
	this.userID,
	this.stringDate,
	this.name,
	this.fcmToken,
	this.beaconName,
	this.vehicleID,
	this.vehicleReg,
	this.make,
	this.model,
	this.starting,
	this.stopping,
	this.moving,
	this.beaconFound,
	this.date,
	this.capacity,
	this.latitude,
	this.longitude,
	this.bearing,
	this.speed,
});

CommuterStartDrivingDTO.fromJson(Map data) {
	this.commuterDrivingID = data['commuterDrivingID'];
	this.userID = data['userID'];
	this.stringDate = data['stringDate'];
	this.name = data['name'];
	this.fcmToken = data['fcmToken'];
	this.beaconName = data['beaconName'];
	this.vehicleID = data['vehicleID'];
	this.vehicleReg = data['vehicleReg'];
	this.make = data['make'];
	this.model = data['model'];
	this.starting = data['starting'];
	this.stopping = data['stopping'];
	this.moving = data['moving'];
	this.beaconFound = data['beaconFound'];
	this.date = data['date'];
	this.capacity = data['capacity'];
	this.latitude = data['latitude'];
	this.longitude = data['longitude'];
	this.bearing = data['bearing'];
	this.speed = data['speed'];
	this.path = data['path'];
}

Map<String, dynamic> toJson() => <String, dynamic>{
	'commuterDrivingID': commuterDrivingID,
	'userID': userID,
	'stringDate': stringDate,
	'name': name,
	'fcmToken': fcmToken,
	'beaconName': beaconName,
	'vehicleID': vehicleID,
	'vehicleReg': vehicleReg,
	'make': make,
	'model': model,
	'starting': starting,
	'stopping': stopping,
	'moving': moving,
	'beaconFound': beaconFound,
	'date': date,
	'capacity': capacity,
	'latitude': latitude,
	'longitude': longitude,
	'bearing': bearing,
	'speed': speed,
	'path': path,
	
};

}