/*
####### Generated by JavaToDart Wed Dec 19 22:12:26 SAST 2018
####### rigged up by AM Esq.
*/

class CountryDTO {
  String countryID;
  String name;
  String status;
  double latitude;
  double longitude;
  int date;
  List provinceList;
  List vehicleTypeList;
  String path;

  CountryDTO({
    this.countryID,
    this.name,
    this.status,
    this.latitude,
    this.longitude,
    this.date,
    this.provinceList,
    this.vehicleTypeList,
  });

  CountryDTO.fromJson(Map data) {
    this.countryID = data['countryID'];
    this.name = data['name'];
    this.status = data['status'];
    this.latitude = data['latitude'];
    this.longitude = data['longitude'];
    this.date = data['date'];
    this.provinceList = data['provinceList'];
    this.vehicleTypeList = data['vehicleTypeList'];
    this.path = data['path'];
  }

  Map<String, dynamic> toJson() => <String, dynamic>{
        'countryID': countryID,
        'name': name,
        'status': status,
        'latitude': latitude,
        'longitude': longitude,
        'date': date,
        'provinceList': provinceList,
        'vehicleTypeList': vehicleTypeList,
        'path': path,
      };
}
