
/*
####### Generated by JavaToDart Wed Dec 19 22:12:26 SAST 2018
####### rigged up by AM Esq.
*/

class DeviceDTO {
	String model;
	String manufacturer;
	String androidVersion;
	String serialNumber;
	String associationID;
	String userID;
	String email;
	int userType;
	String token;
	String path;

DeviceDTO({
	this.model,
	this.manufacturer,
	this.androidVersion,
	this.serialNumber,
	this.associationID,
	this.userID,
	this.email,
	this.userType,
	this.token,
});

DeviceDTO.fromJson(Map data) {
	this.model = data['model'];
	this.manufacturer = data['manufacturer'];
	this.androidVersion = data['androidVersion'];
	this.serialNumber = data['serialNumber'];
	this.associationID = data['associationID'];
	this.userID = data['userID'];
	this.email = data['email'];
	this.userType = data['userType'];
	this.token = data['token'];
	this.path = data['path'];
}

Map<String, dynamic> toJson() => <String, dynamic>{
	'model': model,
	'manufacturer': manufacturer,
	'androidVersion': androidVersion,
	'serialNumber': serialNumber,
	'associationID': associationID,
	'userID': userID,
	'email': email,
	'userType': userType,
	'token': token,
	'path': path,
	
};

}