import 'package:aftarobotlibrary/data/vehicledto.dart';
import 'package:aftarobotlibrary/data/landmarkdto.dart';
import 'package:aftarobotlibrary/data/userdto.dart';
import 'package:aftarobotlibrary/data/devicedto.dart';

/*
####### Generated by JavaToDart Wed Dec 19 22:12:26 SAST 2018
####### rigged up by AM Esq.
*/

class DriverLogDTO {
	String driverLogID;
	String userID;
	String vehicleID;
	String stringDate;
	String nearestAddress;
	VehicleDTO vehicle;
	LandmarkDTO landmark;
	UserDTO user;
	double latitude;
	double longitude;
	int date;
	double accuracy;
	double bearing;
	double speed;
	bool locationRequested;
	DeviceDTO device;
	String path;

DriverLogDTO({
	this.driverLogID,
	this.userID,
	this.vehicleID,
	this.stringDate,
	this.nearestAddress,
	this.vehicle,
	this.landmark,
	this.user,
	this.latitude,
	this.longitude,
	this.date,
	this.accuracy,
	this.bearing,
	this.speed,
	this.locationRequested,
	this.device,
});

DriverLogDTO.fromJson(Map data) {
	this.driverLogID = data['driverLogID'];
	this.userID = data['userID'];
	this.vehicleID = data['vehicleID'];
	this.stringDate = data['stringDate'];
	this.nearestAddress = data['nearestAddress'];
	this.vehicle = data['vehicle'];
	this.landmark = data['landmark'];
	this.user = data['user'];
	this.latitude = data['latitude'];
	this.longitude = data['longitude'];
	this.date = data['date'];
	this.accuracy = data['accuracy'];
	this.bearing = data['bearing'];
	this.speed = data['speed'];
	this.locationRequested = data['locationRequested'];
	this.device = data['device'];
	this.path = data['path'];
}

Map<String, dynamic> toJson() => <String, dynamic>{
	'driverLogID': driverLogID,
	'userID': userID,
	'vehicleID': vehicleID,
	'stringDate': stringDate,
	'nearestAddress': nearestAddress,
	'vehicle': vehicle,
	'landmark': landmark,
	'user': user,
	'latitude': latitude,
	'longitude': longitude,
	'date': date,
	'accuracy': accuracy,
	'bearing': bearing,
	'speed': speed,
	'locationRequested': locationRequested,
	'device': device,
	'path': path,
	
};

}