
/*
####### Generated by JavaToDart Wed Dec 19 22:12:26 SAST 2018
####### rigged up by AM Esq.
*/

class DriverMarshalCampaignDTO {
	String driverMarshalCampaignID;
	String associationID;
	String associationName;
	int startDate;
	int endDate;
	int dateRegistered;
	String stringStartDate;
	String stringEndDate;
	String description;
	String stringDateRegistered;
	int minimumTrips;
	int minimumPickups;
	int minimumCommuters;
	double pointValue;
	double budget;
	String path;

DriverMarshalCampaignDTO({
	this.driverMarshalCampaignID,
	this.associationID,
	this.associationName,
	this.startDate,
	this.endDate,
	this.dateRegistered,
	this.stringStartDate,
	this.stringEndDate,
	this.description,
	this.stringDateRegistered,
	this.minimumTrips,
	this.minimumPickups,
	this.minimumCommuters,
	this.pointValue,
	this.budget,
});

DriverMarshalCampaignDTO.fromJson(Map data) {
	this.driverMarshalCampaignID = data['driverMarshalCampaignID'];
	this.associationID = data['associationID'];
	this.associationName = data['associationName'];
	this.startDate = data['startDate'];
	this.endDate = data['endDate'];
	this.dateRegistered = data['dateRegistered'];
	this.stringStartDate = data['stringStartDate'];
	this.stringEndDate = data['stringEndDate'];
	this.description = data['description'];
	this.stringDateRegistered = data['stringDateRegistered'];
	this.minimumTrips = data['minimumTrips'];
	this.minimumPickups = data['minimumPickups'];
	this.minimumCommuters = data['minimumCommuters'];
	this.pointValue = data['pointValue'];
	this.budget = data['budget'];
	this.path = data['path'];
}

Map<String, dynamic> toJson() => <String, dynamic>{
	'driverMarshalCampaignID': driverMarshalCampaignID,
	'associationID': associationID,
	'associationName': associationName,
	'startDate': startDate,
	'endDate': endDate,
	'dateRegistered': dateRegistered,
	'stringStartDate': stringStartDate,
	'stringEndDate': stringEndDate,
	'description': description,
	'stringDateRegistered': stringDateRegistered,
	'minimumTrips': minimumTrips,
	'minimumPickups': minimumPickups,
	'minimumCommuters': minimumCommuters,
	'pointValue': pointValue,
	'budget': budget,
	'path': path,
	
};

}