
/*
####### Generated by JavaToDart Wed Dec 19 22:12:26 SAST 2018
####### rigged up by AM Esq.
*/

class DriverMarshalCampaignSummaryDTO {
	String driverMarshalCampaignSummaryID;
	String driverMarshalCampaignID;
	String userID;
	String name;
	String associationID;
	String email;
	int dateOfCalculation;
	int dateStart;
	int dateEnd;
	int datePaid;
	String stringDateOfCalculation;
	String stringDateStart;
	String stringDateEnd;
	String stringDatePaid;
	String description;
	int totalTrips;
	int totalPickups;
	int totalCommuters;
	int totalPoints;
	int userType;
	double totalValue;
	double percentageOfBudget;
	bool paid;
	String path;

DriverMarshalCampaignSummaryDTO({
	this.driverMarshalCampaignSummaryID,
	this.driverMarshalCampaignID,
	this.userID,
	this.name,
	this.associationID,
	this.email,
	this.dateOfCalculation,
	this.dateStart,
	this.dateEnd,
	this.datePaid,
	this.stringDateOfCalculation,
	this.stringDateStart,
	this.stringDateEnd,
	this.stringDatePaid,
	this.description,
	this.totalTrips,
	this.totalPickups,
	this.totalCommuters,
	this.totalPoints,
	this.userType,
	this.totalValue,
	this.percentageOfBudget,
	this.paid,
});

DriverMarshalCampaignSummaryDTO.fromJson(Map data) {
	this.driverMarshalCampaignSummaryID = data['driverMarshalCampaignSummaryID'];
	this.driverMarshalCampaignID = data['driverMarshalCampaignID'];
	this.userID = data['userID'];
	this.name = data['name'];
	this.associationID = data['associationID'];
	this.email = data['email'];
	this.dateOfCalculation = data['dateOfCalculation'];
	this.dateStart = data['dateStart'];
	this.dateEnd = data['dateEnd'];
	this.datePaid = data['datePaid'];
	this.stringDateOfCalculation = data['stringDateOfCalculation'];
	this.stringDateStart = data['stringDateStart'];
	this.stringDateEnd = data['stringDateEnd'];
	this.stringDatePaid = data['stringDatePaid'];
	this.description = data['description'];
	this.totalTrips = data['totalTrips'];
	this.totalPickups = data['totalPickups'];
	this.totalCommuters = data['totalCommuters'];
	this.totalPoints = data['totalPoints'];
	this.userType = data['userType'];
	this.totalValue = data['totalValue'];
	this.percentageOfBudget = data['percentageOfBudget'];
	this.paid = data['paid'];
	this.path = data['path'];
}

Map<String, dynamic> toJson() => <String, dynamic>{
	'driverMarshalCampaignSummaryID': driverMarshalCampaignSummaryID,
	'driverMarshalCampaignID': driverMarshalCampaignID,
	'userID': userID,
	'name': name,
	'associationID': associationID,
	'email': email,
	'dateOfCalculation': dateOfCalculation,
	'dateStart': dateStart,
	'dateEnd': dateEnd,
	'datePaid': datePaid,
	'stringDateOfCalculation': stringDateOfCalculation,
	'stringDateStart': stringDateStart,
	'stringDateEnd': stringDateEnd,
	'stringDatePaid': stringDatePaid,
	'description': description,
	'totalTrips': totalTrips,
	'totalPickups': totalPickups,
	'totalCommuters': totalCommuters,
	'totalPoints': totalPoints,
	'userType': userType,
	'totalValue': totalValue,
	'percentageOfBudget': percentageOfBudget,
	'paid': paid,
	'path': path,
	
};

}