
/*
####### Generated by JavaToDart Wed Dec 19 22:12:26 SAST 2018
####### rigged up by AM Esq.
*/

class HeartbeatDTO {
	String heartbeatID;
	String userID;
	String userName;
	String stringDate;
	String fcmToken;
	int date;
	String path;

HeartbeatDTO({
	this.heartbeatID,
	this.userID,
	this.userName,
	this.stringDate,
	this.fcmToken,
	this.date,
});

HeartbeatDTO.fromJson(Map data) {
	this.heartbeatID = data['heartbeatID'];
	this.userID = data['userID'];
	this.userName = data['userName'];
	this.stringDate = data['stringDate'];
	this.fcmToken = data['fcmToken'];
	this.date = data['date'];
	this.path = data['path'];
}

Map<String, dynamic> toJson() => <String, dynamic>{
	'heartbeatID': heartbeatID,
	'userID': userID,
	'userName': userName,
	'stringDate': stringDate,
	'fcmToken': fcmToken,
	'date': date,
	'path': path,
	
};

}