/*
####### Generated by JavaToDart Wed Dec 19 22:12:26 SAST 2018
####### rigged up by AM Esq.
*/

import 'package:aftarobotlibrary/data/routedto.dart';

class MainRankDTO {
  String nickName;
  String path;
  List<RouteDTO> routeSnippets;

  MainRankDTO({
    this.routeSnippets,
    this.nickName,
  });

  MainRankDTO.fromJson(Map data) {
    this.routeSnippets = data['routeSnippets'];
    this.nickName = data['nickName'];
    this.path = data['path'];
  }

  Map<String, dynamic> toJson() => <String, dynamic>{
        'routeSnippets': routeSnippets,
        'nickName': nickName,
        'path': path,
      };
}
