/*
####### Generated by JavaToDart Wed Dec 19 22:12:26 SAST 2018
####### rigged up by AM Esq.
*/

import 'package:aftarobotlibrary/data/routedto.dart';

class MainRankDTO {
  String nickName;
  String path;
  List<RouteDTO> routeSnippets;

  MainRankDTO({
    this.routeSnippets,
    this.nickName,
  });

  MainRankDTO.fromJson(Map data) {
    this.routeSnippets = List();
    if (data['routeSnippets'] != null) {
      try {
        Map<dynamic, dynamic> map = data['routeSnippets'];
        map.forEach((key, value) {
          routeSnippets.add(RouteDTO.fromJson(value));
        });
      } catch (e) {
        List map = data['routeSnippets'];
        map.forEach((value) {
          routeSnippets.add(RouteDTO.fromJson(value));
        });
      }
    }
    this.nickName = data['nickName'];
    this.path = data['path'];
  }

  Map<String, dynamic> toJson() {
    List<Map<String, dynamic>> list = List();
    if (routeSnippets != null && routeSnippets.isNotEmpty) {
      routeSnippets.forEach((rs) {
        list.add(rs.toJson());
      });
    }

    Map<String, dynamic> map = {
      'routeSnippets': list,
      'nickName': nickName,
      'path': path,
    };
    return map;
  }
}
