import 'package:aftarobotlibrary/data/devicedto.dart';

/*
####### Generated by JavaToDart Wed Dec 19 22:12:26 SAST 2018
####### rigged up by AM Esq.
*/

class MarshalArrivalDTO {
	String arrivalID;
	String landmarkID;
	String landmarkName;
	String userID;
	String cityID;
	String cityName;
	String routeID;
	String vehicleID;
	String countryID;
	int dateArrived;
	double latitude;
	double longitude;
	String stringDate;
	DeviceDTO device;
	String path;

MarshalArrivalDTO({
	this.arrivalID,
	this.landmarkID,
	this.landmarkName,
	this.userID,
	this.cityID,
	this.cityName,
	this.routeID,
	this.vehicleID,
	this.countryID,
	this.dateArrived,
	this.latitude,
	this.longitude,
	this.stringDate,
	this.device,
});

MarshalArrivalDTO.fromJson(Map data) {
	this.arrivalID = data['arrivalID'];
	this.landmarkID = data['landmarkID'];
	this.landmarkName = data['landmarkName'];
	this.userID = data['userID'];
	this.cityID = data['cityID'];
	this.cityName = data['cityName'];
	this.routeID = data['routeID'];
	this.vehicleID = data['vehicleID'];
	this.countryID = data['countryID'];
	this.dateArrived = data['dateArrived'];
	this.latitude = data['latitude'];
	this.longitude = data['longitude'];
	this.stringDate = data['stringDate'];
	this.device = data['device'];
	this.path = data['path'];
}

Map<String, dynamic> toJson() => <String, dynamic>{
	'arrivalID': arrivalID,
	'landmarkID': landmarkID,
	'landmarkName': landmarkName,
	'userID': userID,
	'cityID': cityID,
	'cityName': cityName,
	'routeID': routeID,
	'vehicleID': vehicleID,
	'countryID': countryID,
	'dateArrived': dateArrived,
	'latitude': latitude,
	'longitude': longitude,
	'stringDate': stringDate,
	'device': device,
	'path': path,
	
};

}