
/*
####### Generated by JavaToDart Wed Dec 19 22:12:26 SAST 2018
####### rigged up by AM Esq.
*/

class MarshalRouteDTO {
	String userID;
	String routeID;
	String marshalRouteID;
	String marshalID;
	String associationID;
	String routeName;
	String marshalName;
	String stringDate;
	int date;
	List landmarkIDs;
	String path;

MarshalRouteDTO({
	this.userID,
	this.routeID,
	this.marshalRouteID,
	this.marshalID,
	this.associationID,
	this.routeName,
	this.marshalName,
	this.stringDate,
	this.date,
	this.landmarkIDs,
});

MarshalRouteDTO.fromJson(Map data) {
	this.userID = data['userID'];
	this.routeID = data['routeID'];
	this.marshalRouteID = data['marshalRouteID'];
	this.marshalID = data['marshalID'];
	this.associationID = data['associationID'];
	this.routeName = data['routeName'];
	this.marshalName = data['marshalName'];
	this.stringDate = data['stringDate'];
	this.date = data['date'];
	this.landmarkIDs = data['landmarkIDs'];
	this.path = data['path'];
}

Map<String, dynamic> toJson() => <String, dynamic>{
	'userID': userID,
	'routeID': routeID,
	'marshalRouteID': marshalRouteID,
	'marshalID': marshalID,
	'associationID': associationID,
	'routeName': routeName,
	'marshalName': marshalName,
	'stringDate': stringDate,
	'date': date,
	'landmarkIDs': landmarkIDs,
	'path': path,
	
};

}