import 'package:aftarobotlibrary/data/devicedto.dart';

/*
####### Generated by JavaToDart Wed Dec 19 22:12:26 SAST 2018
####### rigged up by AM Esq.
*/

class MessageDTO {
	static const int DEFAULT_PREVIEW_MESSAGE_LENGTH = 0;
	String mID;
	String recepientUserID;
	String senderUserID;
	String messageBody;
	String mDate;
	double latitude;
	double longitude;
	bool notification;
	int date;
	DeviceDTO device;
	String path;

MessageDTO({
	this.mID,
	this.recepientUserID,
	this.senderUserID,
	this.messageBody,
	this.mDate,
	this.latitude,
	this.longitude,
	this.notification,
	this.date,
	this.device,
});

MessageDTO.fromJson(Map data) {
	this.mID = data['mID'];
	this.recepientUserID = data['recepientUserID'];
	this.senderUserID = data['senderUserID'];
	this.messageBody = data['messageBody'];
	this.mDate = data['mDate'];
	this.latitude = data['latitude'];
	this.longitude = data['longitude'];
	this.notification = data['notification'];
	this.date = data['date'];
	this.device = data['device'];
	this.path = data['path'];
}

Map<String, dynamic> toJson() => <String, dynamic>{
	'mID': mID,
	'recepientUserID': recepientUserID,
	'senderUserID': senderUserID,
	'messageBody': messageBody,
	'mDate': mDate,
	'latitude': latitude,
	'longitude': longitude,
	'notification': notification,
	'date': date,
	'device': device,
	'path': path,
	
};

}