import 'package:aftarobotlibrary/data/devicedto.dart';

/*
####### Generated by JavaToDart Wed Dec 19 22:12:26 SAST 2018
####### rigged up by AM Esq.
*/

class PhotoDTO {
	String countryID;
	String cityID;
	String photoID;
	String userID;
	String vehicleID;
	String landmarkID;
	String routeID;
	String associationID;
	String incidentID;
	String announcementID;
	String stringDateTaken;
	String stringDateUploaded;
	int dateTaken;
	int dateUploaded;
	int width;
	int height;
	int bytes;
	double accuracy;
	double latitude;
	double longitude;
	bool defaultPhoto;
	String url;
	String filePath;
	String caption;
	int photoType;
	static const int ASSOCIATION = 0;
	static const int ROUTE = 0;
	static const int LANDMARK = 0;
	static const int USER = 0;
	static const int CITY = 0;
	static const int COUNTRY = 0;
	static const int VEHICLE = 0;
	static const int INCIDENT = 0;
	static const int ANNOUNCEMENT = 0;
	DeviceDTO device;
	String path;

PhotoDTO({
	this.countryID,
	this.cityID,
	this.photoID,
	this.userID,
	this.vehicleID,
	this.landmarkID,
	this.routeID,
	this.associationID,
	this.incidentID,
	this.announcementID,
	this.stringDateTaken,
	this.stringDateUploaded,
	this.dateTaken,
	this.dateUploaded,
	this.width,
	this.height,
	this.bytes,
	this.accuracy,
	this.latitude,
	this.longitude,
	this.defaultPhoto,
	this.url,
	this.filePath,
	this.caption,
	this.photoType,
	this.device,
});

PhotoDTO.fromJson(Map data) {
	this.countryID = data['countryID'];
	this.cityID = data['cityID'];
	this.photoID = data['photoID'];
	this.userID = data['userID'];
	this.vehicleID = data['vehicleID'];
	this.landmarkID = data['landmarkID'];
	this.routeID = data['routeID'];
	this.associationID = data['associationID'];
	this.incidentID = data['incidentID'];
	this.announcementID = data['announcementID'];
	this.stringDateTaken = data['stringDateTaken'];
	this.stringDateUploaded = data['stringDateUploaded'];
	this.dateTaken = data['dateTaken'];
	this.dateUploaded = data['dateUploaded'];
	this.width = data['width'];
	this.height = data['height'];
	this.bytes = data['bytes'];
	this.accuracy = data['accuracy'];
	this.latitude = data['latitude'];
	this.longitude = data['longitude'];
	this.defaultPhoto = data['defaultPhoto'];
	this.url = data['url'];
	this.filePath = data['filePath'];
	this.caption = data['caption'];
	this.photoType = data['photoType'];
	this.device = data['device'];
	this.path = data['path'];
}

Map<String, dynamic> toJson() => <String, dynamic>{
	'countryID': countryID,
	'cityID': cityID,
	'photoID': photoID,
	'userID': userID,
	'vehicleID': vehicleID,
	'landmarkID': landmarkID,
	'routeID': routeID,
	'associationID': associationID,
	'incidentID': incidentID,
	'announcementID': announcementID,
	'stringDateTaken': stringDateTaken,
	'stringDateUploaded': stringDateUploaded,
	'dateTaken': dateTaken,
	'dateUploaded': dateUploaded,
	'width': width,
	'height': height,
	'bytes': bytes,
	'accuracy': accuracy,
	'latitude': latitude,
	'longitude': longitude,
	'defaultPhoto': defaultPhoto,
	'url': url,
	'filePath': filePath,
	'caption': caption,
	'photoType': photoType,
	'device': device,
	'path': path,
	
};

}