import 'package:aftarobotlibrary/data/vehicledto.dart';

/*
####### Generated by JavaToDart Wed Dec 19 22:12:26 SAST 2018
####### rigged up by AM Esq.
*/

class PickUpDTO {
	int pickupDate;
	String associationID;
	String cityID;
	String routeID;
	String landmarkID;
	String userID;
	String ownerID;
	String vehicleID;
	String vehicleReg;
	String associationName;
	String cityName;
	String routeName;
	String ownerName;
	String landmarkName;
	String stringPickUpDate;
	String pickUpID;
	String driverID;
	String marshalID;
	String driverName;
	String marshalName;
	String commuterRequestID;
	String userFCMtoken;
	VehicleDTO vehicle;
	String path;

PickUpDTO({
	this.pickupDate,
	this.associationID,
	this.cityID,
	this.routeID,
	this.landmarkID,
	this.userID,
	this.ownerID,
	this.vehicleID,
	this.vehicleReg,
	this.associationName,
	this.cityName,
	this.routeName,
	this.ownerName,
	this.landmarkName,
	this.stringPickUpDate,
	this.pickUpID,
	this.driverID,
	this.marshalID,
	this.driverName,
	this.marshalName,
	this.commuterRequestID,
	this.userFCMtoken,
	this.vehicle,
});

PickUpDTO.fromJson(Map data) {
	this.pickupDate = data['pickupDate'];
	this.associationID = data['associationID'];
	this.cityID = data['cityID'];
	this.routeID = data['routeID'];
	this.landmarkID = data['landmarkID'];
	this.userID = data['userID'];
	this.ownerID = data['ownerID'];
	this.vehicleID = data['vehicleID'];
	this.vehicleReg = data['vehicleReg'];
	this.associationName = data['associationName'];
	this.cityName = data['cityName'];
	this.routeName = data['routeName'];
	this.ownerName = data['ownerName'];
	this.landmarkName = data['landmarkName'];
	this.stringPickUpDate = data['stringPickUpDate'];
	this.pickUpID = data['pickUpID'];
	this.driverID = data['driverID'];
	this.marshalID = data['marshalID'];
	this.driverName = data['driverName'];
	this.marshalName = data['marshalName'];
	this.commuterRequestID = data['commuterRequestID'];
	this.userFCMtoken = data['userFCMtoken'];
	this.vehicle = data['vehicle'];
	this.path = data['path'];
}

Map<String, dynamic> toJson() => <String, dynamic>{
	'pickupDate': pickupDate,
	'associationID': associationID,
	'cityID': cityID,
	'routeID': routeID,
	'landmarkID': landmarkID,
	'userID': userID,
	'ownerID': ownerID,
	'vehicleID': vehicleID,
	'vehicleReg': vehicleReg,
	'associationName': associationName,
	'cityName': cityName,
	'routeName': routeName,
	'ownerName': ownerName,
	'landmarkName': landmarkName,
	'stringPickUpDate': stringPickUpDate,
	'pickUpID': pickUpID,
	'driverID': driverID,
	'marshalID': marshalID,
	'driverName': driverName,
	'marshalName': marshalName,
	'commuterRequestID': commuterRequestID,
	'userFCMtoken': userFCMtoken,
	'vehicle': vehicle,
	'path': path,
	
};

}