
/*
####### Generated by JavaToDart Wed Dec 19 22:12:26 SAST 2018
####### rigged up by AM Esq.
*/

class PlaceDTO {
	String name;
	String googlePlaceID;
	String placeID;
	String address;
	double latitude;
	double longitude;
	String path;

PlaceDTO({
	this.name,
	this.googlePlaceID,
	this.placeID,
	this.address,
	this.latitude,
	this.longitude,
});

PlaceDTO.fromJson(Map data) {
	this.name = data['name'];
	this.googlePlaceID = data['googlePlaceID'];
	this.placeID = data['placeID'];
	this.address = data['address'];
	this.latitude = data['latitude'];
	this.longitude = data['longitude'];
	this.path = data['path'];
}

Map<String, dynamic> toJson() => <String, dynamic>{
	'name': name,
	'googlePlaceID': googlePlaceID,
	'placeID': placeID,
	'address': address,
	'latitude': latitude,
	'longitude': longitude,
	'path': path,
	
};

}