
/*
####### Generated by JavaToDart Wed Dec 19 22:12:26 SAST 2018
####### rigged up by AM Esq.
*/

class ProvinceDTO {
	String provinceID;
	String countryID;
	String name;
	String status;
	double latitude;
	double longitude;
	int date;
	String path;

ProvinceDTO({
	this.provinceID,
	this.countryID,
	this.name,
	this.status,
	this.latitude,
	this.longitude,
	this.date,
});

ProvinceDTO.fromJson(Map data) {
	this.provinceID = data['provinceID'];
	this.countryID = data['countryID'];
	this.name = data['name'];
	this.status = data['status'];
	this.latitude = data['latitude'];
	this.longitude = data['longitude'];
	this.date = data['date'];
	this.path = data['path'];
}

Map<String, dynamic> toJson() => <String, dynamic>{
	'provinceID': provinceID,
	'countryID': countryID,
	'name': name,
	'status': status,
	'latitude': latitude,
	'longitude': longitude,
	'date': date,
	'path': path,
	
};

}