
/*
####### Generated by JavaToDart Wed Dec 19 22:12:26 SAST 2018
####### rigged up by AM Esq.
*/

class RatingDTO {
	static const int DRIVER = 0;
	static const int TRIP = 0;
	static const int LANDMARK = 0;
	static const int VEHICLE = 0;
	static const int OVERALL_EXPERIENCE = 0;
	static const int SAFETY_RATING = 0;
	static const int QUESTION_RATING = 0;
	static const int TERRIBLE = 0;
	static const int POOR = 0;
	static const int AVERAGE = 0;
	static const int GOOD = 0;
	static const int EXCELLENT = 0;
	String userID;
	String routeID;
	String landmarkID;
	String driverID;
	String vehicleID;
	String marshalID;
	String tripID;
	String ratingID;
	String ownerID;
	String associationID;
	double ratingType;
	double ratingLevel;
	String remarks;
	String fcmToken;
	String ratingTypeName;
	String answer;
	String stringDate;
	String ratingDate;
	int date;
	int day;
	int month;
	int year;
	String path;

RatingDTO({
	this.userID,
	this.routeID,
	this.landmarkID,
	this.driverID,
	this.vehicleID,
	this.marshalID,
	this.tripID,
	this.ratingID,
	this.ownerID,
	this.associationID,
	this.ratingType,
	this.ratingLevel,
	this.remarks,
	this.fcmToken,
	this.ratingTypeName,
	this.answer,
	this.stringDate,
	this.ratingDate,
	this.date,
	this.day,
	this.month,
	this.year,
});

RatingDTO.fromJson(Map data) {
	this.userID = data['userID'];
	this.routeID = data['routeID'];
	this.landmarkID = data['landmarkID'];
	this.driverID = data['driverID'];
	this.vehicleID = data['vehicleID'];
	this.marshalID = data['marshalID'];
	this.tripID = data['tripID'];
	this.ratingID = data['ratingID'];
	this.ownerID = data['ownerID'];
	this.associationID = data['associationID'];
	this.ratingType = data['ratingType'];
	this.ratingLevel = data['ratingLevel'];
	this.remarks = data['remarks'];
	this.fcmToken = data['fcmToken'];
	this.ratingTypeName = data['ratingTypeName'];
	this.answer = data['answer'];
	this.stringDate = data['stringDate'];
	this.ratingDate = data['ratingDate'];
	this.date = data['date'];
	this.day = data['day'];
	this.month = data['month'];
	this.year = data['year'];
	this.path = data['path'];
}

Map<String, dynamic> toJson() => <String, dynamic>{
	'userID': userID,
	'routeID': routeID,
	'landmarkID': landmarkID,
	'driverID': driverID,
	'vehicleID': vehicleID,
	'marshalID': marshalID,
	'tripID': tripID,
	'ratingID': ratingID,
	'ownerID': ownerID,
	'associationID': associationID,
	'ratingType': ratingType,
	'ratingLevel': ratingLevel,
	'remarks': remarks,
	'fcmToken': fcmToken,
	'ratingTypeName': ratingTypeName,
	'answer': answer,
	'stringDate': stringDate,
	'ratingDate': ratingDate,
	'date': date,
	'day': day,
	'month': month,
	'year': year,
	'path': path,
	
};

}