
/*
####### Generated by JavaToDart Wed Dec 19 22:12:26 SAST 2018
####### rigged up by AM Esq.
*/

class RatingLevelDTO {
	int number;
	String description;
	String path;

RatingLevelDTO({
	this.number,
	this.description,
});

RatingLevelDTO.fromJson(Map data) {
	this.number = data['number'];
	this.description = data['description'];
	this.path = data['path'];
}

Map<String, dynamic> toJson() => <String, dynamic>{
	'number': number,
	'description': description,
	'path': path,
	
};

}