import 'package:aftarobotlibrary/data/landmarkdto.dart';
import 'package:aftarobotlibrary/data/spatialinfodto.dart';
import 'package:aftarobotlibrary/data/userdto.dart';

/*
####### Generated by JavaToDart Wed Dec 19 22:12:26 SAST 2018
####### rigged up by AM Esq.
*/

class RouteDTO {
  String routeID;
  String associationID;
  String countryID;
  String provinceID;
  String cityID;
  String name;
  String status;
  String associationName;
  String cityName;
  String countryName;
  String routeNumber;
  String stringDate;
  String color;
  int date;
  int cacheDate;
  UserDTO user;
  List landmarkList;
  UserDTO routeBuilder;
  String path;
  List<LandmarkDTO> landmarks;
  List<SpatialInfoDTO> spatialInfos;

  RouteDTO({
    this.routeID,
    this.associationID,
    this.countryID,
    this.provinceID,
    this.cityID,
    this.name,
    this.status,
    this.associationName,
    this.cityName,
    this.countryName,
    this.routeNumber,
    this.stringDate,
    this.color,
    this.date,
    this.cacheDate,
    this.routeBuilder,
    this.landmarks,
    this.spatialInfos,
    this.landmarkList,
  });

  RouteDTO.fromJson(Map data) {
    this.routeID = data['routeID'];
    this.associationID = data['associationID'];
    this.countryID = data['countryID'];
    this.provinceID = data['provinceID'];
    this.cityID = data['cityID'];
    this.name = data['name'];
    this.status = data['status'];
    this.associationName = data['associationName'];
    this.cityName = data['cityName'];
    this.countryName = data['countryName'];
    this.routeNumber = data['routeNumber'];
    this.stringDate = data['stringDate'];
    this.color = data['color'];
    this.date = data['date'];
    this.cacheDate = data['cacheDate'];
    this.routeBuilder = data['routeBuilder'];
    this.landmarks = data['landmarks'];
    this.spatialInfos = data['spatialInfos'];
    this.landmarkList = data['landmarkList'];
    this.path = data['path'];
  }

  Map<String, dynamic> toJson() => <String, dynamic>{
        'routeID': routeID,
        'associationID': associationID,
        'countryID': countryID,
        'provinceID': provinceID,
        'cityID': cityID,
        'name': name,
        'status': status,
        'associationName': associationName,
        'cityName': cityName,
        'countryName': countryName,
        'routeNumber': routeNumber,
        'stringDate': stringDate,
        'color': color,
        'date': date,
        'cacheDate': cacheDate,
        'routeBuilder': routeBuilder,
        'landmarks': landmarks,
        'spatialInfos': spatialInfos,
        'landmarkList': landmarkList,
        'path': path,
      };
}
