
/*
####### Generated by JavaToDart Wed Dec 19 22:12:26 SAST 2018
####### rigged up by AM Esq.
*/

class RouteBuilderLocationResponseDTO {
	String routeBuilderLocationResponseID;
	String message;
	String stringDate;
	String from;
	String fcmToken;
	int date;
	String builderName;
	String userID;
	double latitude;
	double longitude;
	String path;

RouteBuilderLocationResponseDTO({
	this.routeBuilderLocationResponseID,
	this.message,
	this.stringDate,
	this.from,
	this.fcmToken,
	this.date,
	this.builderName,
	this.userID,
	this.latitude,
	this.longitude,
});

RouteBuilderLocationResponseDTO.fromJson(Map data) {
	this.routeBuilderLocationResponseID = data['routeBuilderLocationResponseID'];
	this.message = data['message'];
	this.stringDate = data['stringDate'];
	this.from = data['from'];
	this.fcmToken = data['fcmToken'];
	this.date = data['date'];
	this.builderName = data['builderName'];
	this.userID = data['userID'];
	this.latitude = data['latitude'];
	this.longitude = data['longitude'];
	this.path = data['path'];
}

Map<String, dynamic> toJson() => <String, dynamic>{
	'routeBuilderLocationResponseID': routeBuilderLocationResponseID,
	'message': message,
	'stringDate': stringDate,
	'from': from,
	'fcmToken': fcmToken,
	'date': date,
	'builderName': builderName,
	'userID': userID,
	'latitude': latitude,
	'longitude': longitude,
	'path': path,
	
};

}