
/*
####### Generated by JavaToDart Wed Dec 19 22:12:26 SAST 2018
####### rigged up by AM Esq.
*/

class RoutePointDTO {
	double latitude;
	double longitude;
	String path;

RoutePointDTO({
	this.latitude,
	this.longitude,
});

RoutePointDTO.fromJson(Map data) {
	this.latitude = data['latitude'];
	this.longitude = data['longitude'];
	this.path = data['path'];
}

Map<String, dynamic> toJson() => <String, dynamic>{
	'latitude': latitude,
	'longitude': longitude,
	'path': path,
	
};

}