
/*
####### Generated by JavaToDart Wed Dec 19 22:12:26 SAST 2018
####### rigged up by AM Esq.
*/

class SearchVehicleDTO {
	int vehicleID;
	String reg;
	String path;

SearchVehicleDTO({
	this.vehicleID,
	this.reg,
});

SearchVehicleDTO.fromJson(Map data) {
	this.vehicleID = data['vehicleID'];
	this.reg = data['reg'];
	this.path = data['path'];
}

Map<String, dynamic> toJson() => <String, dynamic>{
	'vehicleID': vehicleID,
	'reg': reg,
	'path': path,
	
};

}