import 'package:aftarobotlibrary/data/landmarkdto.dart';

/*
####### Generated by JavaToDart Wed Dec 19 22:12:26 SAST 2018
####### rigged up by AM Esq.
*/

class SpatialInfoDTO {
  int estimatedTime;
  double distance;
  String routeID;
  String distanceID;
  String codedPath;
  String stringEstimatedTime;
  String stringDistance;
  LandmarkDTO fromLandmark;
  LandmarkDTO toLandmark;
  String path;

  SpatialInfoDTO({
    this.estimatedTime,
    this.distance,
    this.routeID,
    this.distanceID,
    this.codedPath,
    this.stringEstimatedTime,
    this.stringDistance,
    this.fromLandmark,
    this.toLandmark,
  });

  SpatialInfoDTO.fromJson(Map data) {
    this.estimatedTime = data['estimatedTime'];
    if (data['distance'] != null) {
      if (data['distance'] is double) {
        this.distance = data['distance'];
      } else {
        this.distance = double.parse(data['distance'].toString());
      }
    }

    this.routeID = data['routeID'];
    this.distanceID = data['distanceID'];
    this.codedPath = data['codedPath'];
    this.stringEstimatedTime = data['stringEstimatedTime'];
    this.stringDistance = data['stringDistance'];
    if (data['fromLandmark'] != null) {
      this.fromLandmark = LandmarkDTO.fromJson(data['fromLandmark']);
    }
    if (data['toLandmark'] != null) {
      this.toLandmark = LandmarkDTO.fromJson(data['toLandmark']);
    }
    this.path = data['path'];
  }

  Map<String, dynamic> toJson() {
    Map<String, dynamic> mFrom;
    Map<String, dynamic> mTo;
    if (fromLandmark != null) {
      mFrom = fromLandmark.toJson();
    }
    if (toLandmark != null) {
      mTo = toLandmark.toJson();
    }
    Map<String, dynamic> map = {
      'estimatedTime': estimatedTime,
      'distance': distance,
      'routeID': routeID,
      'distanceID': distanceID,
      'codedPath': codedPath,
      'stringEstimatedTime': stringEstimatedTime,
      'stringDistance': stringDistance,
      'fromLandmark': mFrom,
      'toLandmark': mTo,
      'path': path,
    };
    return map;
  }
}
