import 'package:aftarobotlibrary/data/landmarkdto.dart';

/*
####### Generated by JavaToDart Wed Dec 19 22:12:26 SAST 2018
####### rigged up by AM Esq.
*/

class SpatialInfoDTO {
  int estimatedTime;
  double distance;
  String routeID;
  String distanceID;
  String codedPath;
  String stringEstimatedTime;
  String stringDistance;
  LandmarkDTO fromLandmark;
  LandmarkDTO toLandmark;
  String path;

  SpatialInfoDTO({
    this.estimatedTime,
    this.distance,
    this.routeID,
    this.distanceID,
    this.codedPath,
    this.stringEstimatedTime,
    this.stringDistance,
    this.fromLandmark,
    this.toLandmark,
  });

  SpatialInfoDTO.fromJson(Map data) {
    this.estimatedTime = data['estimatedTime'];
    this.distance = data['distance'];
    this.routeID = data['routeID'];
    this.distanceID = data['distanceID'];
    this.codedPath = data['codedPath'];
    this.stringEstimatedTime = data['stringEstimatedTime'];
    this.stringDistance = data['stringDistance'];
    this.fromLandmark = data['fromLandmark'];
    this.toLandmark = data['toLandmark'];
    this.path = data['path'];
  }

  Map<String, dynamic> toJson() => <String, dynamic>{
        'estimatedTime': estimatedTime,
        'distance': distance,
        'routeID': routeID,
        'distanceID': distanceID,
        'codedPath': codedPath,
        'stringEstimatedTime': stringEstimatedTime,
        'stringDistance': stringDistance,
        'fromLandmark': fromLandmark,
        'toLandmark': toLandmark,
        'path': path,
      };
}
