import 'package:aftarobotlibrary/data/vehicledto.dart';
import 'package:aftarobotlibrary/data/userdto.dart';

/*
####### Generated by JavaToDart Wed Dec 19 22:12:26 SAST 2018
####### rigged up by AM Esq.
*/

class StoppingVehicleDTO {
	String stoppingVehicleID;
	String vehicleID;
	String userID;
	String stringDate;
	String vehicleReg;
	String ownerID;
	String associationID;
	double latitude;
	double longitude;
	VehicleDTO vehicle;
	UserDTO user;
	int date;
	String path;

StoppingVehicleDTO({
	this.stoppingVehicleID,
	this.vehicleID,
	this.userID,
	this.stringDate,
	this.vehicleReg,
	this.ownerID,
	this.associationID,
	this.latitude,
	this.longitude,
	this.vehicle,
	this.user,
	this.date,
});

StoppingVehicleDTO.fromJson(Map data) {
	this.stoppingVehicleID = data['stoppingVehicleID'];
	this.vehicleID = data['vehicleID'];
	this.userID = data['userID'];
	this.stringDate = data['stringDate'];
	this.vehicleReg = data['vehicleReg'];
	this.ownerID = data['ownerID'];
	this.associationID = data['associationID'];
	this.latitude = data['latitude'];
	this.longitude = data['longitude'];
	this.vehicle = data['vehicle'];
	this.user = data['user'];
	this.date = data['date'];
	this.path = data['path'];
}

Map<String, dynamic> toJson() => <String, dynamic>{
	'stoppingVehicleID': stoppingVehicleID,
	'vehicleID': vehicleID,
	'userID': userID,
	'stringDate': stringDate,
	'vehicleReg': vehicleReg,
	'ownerID': ownerID,
	'associationID': associationID,
	'latitude': latitude,
	'longitude': longitude,
	'vehicle': vehicle,
	'user': user,
	'date': date,
	'path': path,
	
};

}