
/*
####### Generated by JavaToDart Wed Dec 19 22:12:26 SAST 2018
####### rigged up by AM Esq.
*/

class TravelBuddyDTO {
	String travelBuddyID;
	String userID;
	String buddyID;
	String buddyName;
	String buddyEmail;
	String buddyPhone;
	String stringDate;
	int date;
	String buddyFCMtoken;
	bool active;
	String path;

TravelBuddyDTO({
	this.travelBuddyID,
	this.userID,
	this.buddyID,
	this.buddyName,
	this.buddyEmail,
	this.buddyPhone,
	this.stringDate,
	this.date,
	this.buddyFCMtoken,
	this.active,
});

TravelBuddyDTO.fromJson(Map data) {
	this.travelBuddyID = data['travelBuddyID'];
	this.userID = data['userID'];
	this.buddyID = data['buddyID'];
	this.buddyName = data['buddyName'];
	this.buddyEmail = data['buddyEmail'];
	this.buddyPhone = data['buddyPhone'];
	this.stringDate = data['stringDate'];
	this.date = data['date'];
	this.buddyFCMtoken = data['buddyFCMtoken'];
	this.active = data['active'];
	this.path = data['path'];
}

Map<String, dynamic> toJson() => <String, dynamic>{
	'travelBuddyID': travelBuddyID,
	'userID': userID,
	'buddyID': buddyID,
	'buddyName': buddyName,
	'buddyEmail': buddyEmail,
	'buddyPhone': buddyPhone,
	'stringDate': stringDate,
	'date': date,
	'buddyFCMtoken': buddyFCMtoken,
	'active': active,
	'path': path,
	
};

}