
/*
####### Generated by JavaToDart Wed Dec 19 22:12:26 SAST 2018
####### rigged up by AM Esq.
*/

class UserWalkingDTO {
	String userID;
	String name;
	String associationID;
	String userDescription;
	double latitude;
	double longitude;
	int date;
	int userType;
	String path;

UserWalkingDTO({
	this.userID,
	this.name,
	this.associationID,
	this.userDescription,
	this.latitude,
	this.longitude,
	this.date,
	this.userType,
});

UserWalkingDTO.fromJson(Map data) {
	this.userID = data['userID'];
	this.name = data['name'];
	this.associationID = data['associationID'];
	this.userDescription = data['userDescription'];
	this.latitude = data['latitude'];
	this.longitude = data['longitude'];
	this.date = data['date'];
	this.userType = data['userType'];
	this.path = data['path'];
}

Map<String, dynamic> toJson() => <String, dynamic>{
	'userID': userID,
	'name': name,
	'associationID': associationID,
	'userDescription': userDescription,
	'latitude': latitude,
	'longitude': longitude,
	'date': date,
	'userType': userType,
	'path': path,
	
};

}