import 'package:aftarobotlibrary/data/devicedto.dart';
import 'package:aftarobotlibrary/data/landmarkdto.dart';
import 'package:aftarobotlibrary/data/vehicledto.dart';

/*
####### Generated by JavaToDart Wed Dec 19 22:12:26 SAST 2018
####### rigged up by AM Esq.
*/

class UserDTO {
  int userType;
  String userID;
  String uid;
  String name;
  String countryID;
  String associationID;
  String associationName;
  String fcmToken;
  String email;
  String cellphone;
  String password;
  String userDescription;
  String stringDateRegistered;
  String hyperTrackUserID;
  LandmarkDTO morningLandmark;
  LandmarkDTO afternoonLandmark;
  int dateRegistered;
  bool activeFlag;
  bool researchConsent;
  String gender;
  String address;
  String idNumber;
  DeviceDTO device;
  VehicleDTO vehicle;
  String path;

  UserDTO({
    this.userType,
    this.userID,
    this.uid,
    this.name,
    this.countryID,
    this.associationID,
    this.associationName,
    this.fcmToken,
    this.email,
    this.cellphone,
    this.password,
    this.userDescription,
    this.stringDateRegistered,
    this.hyperTrackUserID,
    this.morningLandmark,
    this.afternoonLandmark,
    this.dateRegistered,
    this.activeFlag,
    this.researchConsent,
    this.gender,
    this.address,
    this.idNumber,
    this.device,
    this.vehicle,
  });

  UserDTO.fromJson(Map data) {
    this.userType = data['userType'];
    this.userID = data['userID'];
    this.uid = data['uid'];
    this.name = data['name'];
    this.countryID = data['countryID'];
    this.associationID = data['associationID'];
    this.associationName = data['associationName'];
    this.fcmToken = data['fcmToken'];
    this.email = data['email'];
    this.cellphone = data['cellphone'];
    this.password = data['password'];
    this.userDescription = data['userDescription'];
    this.stringDateRegistered = data['stringDateRegistered'];
    this.hyperTrackUserID = data['hyperTrackUserID'];
    this.morningLandmark = data['morningLandmark'];
    this.afternoonLandmark = data['afternoonLandmark'];
    this.dateRegistered = data['dateRegistered'];
    this.activeFlag = data['activeFlag'];
    this.researchConsent = data['researchConsent'];
    this.gender = data['gender'];
    this.address = data['address'];
    this.idNumber = data['idNumber'];
    if (data['device'] != null) {
      this.device = DeviceDTO.fromJson(data['device']);
    }

//    this.vehicle = data['vehicle'];
    this.path = data['path'];
  }

  Map<String, dynamic> toJson() {
    Map<String, dynamic> mDev;
    if (device != null) {
      mDev = device.toJson();
    }
    Map<String, dynamic> map = {
      'userType': userType,
      'userID': userID,
      'uid': uid,
      'name': name,
      'countryID': countryID,
      'associationID': associationID,
      'associationName': associationName,
      'fcmToken': fcmToken,
      'email': email,
      'cellphone': cellphone,
      'password': password,
      'userDescription': userDescription,
      'stringDateRegistered': stringDateRegistered,
      'hyperTrackUserID': hyperTrackUserID,
      'morningLandmark': morningLandmark,
      'afternoonLandmark': afternoonLandmark,
      'dateRegistered': dateRegistered,
      'activeFlag': activeFlag,
      'researchConsent': researchConsent,
      'gender': gender,
      'address': address,
      'idNumber': idNumber,
      'device': mDev,
      'vehicle': vehicle,
      'path': path,
    };
    return map;
  }
}
