import 'package:aftarobotlibrary/data/vehicledto.dart';
import 'package:aftarobotlibrary/data/devicedto.dart';

/*
####### Generated by JavaToDart Wed Dec 19 22:12:26 SAST 2018
####### rigged up by AM Esq.
*/

class VehicleArrivalDTO {
	String arrivalID;
	String landmarkID;
	String landmarkName;
	String userID;
	String driverName;
	String cityID;
	String cityName;
	String routeID;
	String vehicleID;
	String associationID;
	String routeName;
	String associationName;
	String countryID;
	int dateArrived;
	double latitude;
	double longitude;
	bool dispatched;
	VehicleDTO vehicle;
	String stringDate;
	DeviceDTO device;
	String path;

VehicleArrivalDTO({
	this.arrivalID,
	this.landmarkID,
	this.landmarkName,
	this.userID,
	this.driverName,
	this.cityID,
	this.cityName,
	this.routeID,
	this.vehicleID,
	this.associationID,
	this.routeName,
	this.associationName,
	this.countryID,
	this.dateArrived,
	this.latitude,
	this.longitude,
	this.dispatched,
	this.vehicle,
	this.stringDate,
	this.device,
});

VehicleArrivalDTO.fromJson(Map data) {
	this.arrivalID = data['arrivalID'];
	this.landmarkID = data['landmarkID'];
	this.landmarkName = data['landmarkName'];
	this.userID = data['userID'];
	this.driverName = data['driverName'];
	this.cityID = data['cityID'];
	this.cityName = data['cityName'];
	this.routeID = data['routeID'];
	this.vehicleID = data['vehicleID'];
	this.associationID = data['associationID'];
	this.routeName = data['routeName'];
	this.associationName = data['associationName'];
	this.countryID = data['countryID'];
	this.dateArrived = data['dateArrived'];
	this.latitude = data['latitude'];
	this.longitude = data['longitude'];
	this.dispatched = data['dispatched'];
	this.vehicle = data['vehicle'];
	this.stringDate = data['stringDate'];
	this.device = data['device'];
	this.path = data['path'];
}

Map<String, dynamic> toJson() => <String, dynamic>{
	'arrivalID': arrivalID,
	'landmarkID': landmarkID,
	'landmarkName': landmarkName,
	'userID': userID,
	'driverName': driverName,
	'cityID': cityID,
	'cityName': cityName,
	'routeID': routeID,
	'vehicleID': vehicleID,
	'associationID': associationID,
	'routeName': routeName,
	'associationName': associationName,
	'countryID': countryID,
	'dateArrived': dateArrived,
	'latitude': latitude,
	'longitude': longitude,
	'dispatched': dispatched,
	'vehicle': vehicle,
	'stringDate': stringDate,
	'device': device,
	'path': path,
	
};

}