import 'package:aftarobotlibrary/data/vehicledto.dart';
import 'package:aftarobotlibrary/data/devicedto.dart';

/*
####### Generated by JavaToDart Wed Dec 19 22:12:26 SAST 2018
####### rigged up by AM Esq.
*/

class VehicleDepartureDTO {
	String departureID;
	String landmarkID;
	String landmarkName;
	String userID;
	String driverName;
	String cityID;
	String cityName;
	String routeID;
	String vehicleID;
	String associationID;
	String associationName;
	String countryID;
	int dateDeparted;
	VehicleDTO vehicle;
	String stringDate;
	DeviceDTO device;
	String path;

VehicleDepartureDTO({
	this.departureID,
	this.landmarkID,
	this.landmarkName,
	this.userID,
	this.driverName,
	this.cityID,
	this.cityName,
	this.routeID,
	this.vehicleID,
	this.associationID,
	this.associationName,
	this.countryID,
	this.dateDeparted,
	this.vehicle,
	this.stringDate,
	this.device,
});

VehicleDepartureDTO.fromJson(Map data) {
	this.departureID = data['departureID'];
	this.landmarkID = data['landmarkID'];
	this.landmarkName = data['landmarkName'];
	this.userID = data['userID'];
	this.driverName = data['driverName'];
	this.cityID = data['cityID'];
	this.cityName = data['cityName'];
	this.routeID = data['routeID'];
	this.vehicleID = data['vehicleID'];
	this.associationID = data['associationID'];
	this.associationName = data['associationName'];
	this.countryID = data['countryID'];
	this.dateDeparted = data['dateDeparted'];
	this.vehicle = data['vehicle'];
	this.stringDate = data['stringDate'];
	this.device = data['device'];
	this.path = data['path'];
}

Map<String, dynamic> toJson() => <String, dynamic>{
	'departureID': departureID,
	'landmarkID': landmarkID,
	'landmarkName': landmarkName,
	'userID': userID,
	'driverName': driverName,
	'cityID': cityID,
	'cityName': cityName,
	'routeID': routeID,
	'vehicleID': vehicleID,
	'associationID': associationID,
	'associationName': associationName,
	'countryID': countryID,
	'dateDeparted': dateDeparted,
	'vehicle': vehicle,
	'stringDate': stringDate,
	'device': device,
	'path': path,
	
};

}