
/*
####### Generated by JavaToDart Wed Dec 19 22:12:26 SAST 2018
####### rigged up by AM Esq.
*/

class VehicleTypeDTO {
	int capacity;
	String vehicleTypeID;
	String make;
	String model;
	String countryID;
	String path;

VehicleTypeDTO({
	this.capacity,
	this.vehicleTypeID,
	this.make,
	this.model,
	this.countryID,
});

VehicleTypeDTO.fromJson(Map data) {
	this.capacity = data['capacity'];
	this.vehicleTypeID = data['vehicleTypeID'];
	this.make = data['make'];
	this.model = data['model'];
	this.countryID = data['countryID'];
	this.path = data['path'];
}

Map<String, dynamic> toJson() => <String, dynamic>{
	'capacity': capacity,
	'vehicleTypeID': vehicleTypeID,
	'make': make,
	'model': model,
	'countryID': countryID,
	'path': path,
	
};

}