
/*
####### Generated by JavaToDart Wed Dec 19 22:12:26 SAST 2018
####### rigged up by AM Esq.
*/

class VehicleInfoDTO {
	int vehicleProfileID;
	String type;
	String year;
	String make;
	int capacity;
	String operatingLicence;
	int operatingLicenceExpDate;
	int date;
	String status;
	int vehicleID;
	String path;

VehicleInfoDTO({
	this.vehicleProfileID,
	this.type,
	this.year,
	this.make,
	this.capacity,
	this.operatingLicence,
	this.operatingLicenceExpDate,
	this.date,
	this.status,
	this.vehicleID,
});

VehicleInfoDTO.fromJson(Map data) {
	this.vehicleProfileID = data['vehicleProfileID'];
	this.type = data['type'];
	this.year = data['year'];
	this.make = data['make'];
	this.capacity = data['capacity'];
	this.operatingLicence = data['operatingLicence'];
	this.operatingLicenceExpDate = data['operatingLicenceExpDate'];
	this.date = data['date'];
	this.status = data['status'];
	this.vehicleID = data['vehicleID'];
	this.path = data['path'];
}

Map<String, dynamic> toJson() => <String, dynamic>{
	'vehicleProfileID': vehicleProfileID,
	'type': type,
	'year': year,
	'make': make,
	'capacity': capacity,
	'operatingLicence': operatingLicence,
	'operatingLicenceExpDate': operatingLicenceExpDate,
	'date': date,
	'status': status,
	'vehicleID': vehicleID,
	'path': path,
	
};

}